.TH "_group_16" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_group_16
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdata_u8\fP [2]"
.br
.ti -1c
.RI "char \fBdata_8\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBdata_u16\fP"
.br
.ti -1c
.RI "int \fBdata_16\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file util\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int data_16"

.PP
Definition at line 48 of file util\&.h\&.
.SS "char data_8[2]"

.PP
Definition at line 46 of file util\&.h\&.
.SS "unsigned int data_u16"

.PP
Definition at line 47 of file util\&.h\&.
.SS "unsigned char data_u8[2]"

.PP
Definition at line 45 of file util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
