.TH "_group_64" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_group_64
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBdata_fp\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBdata_u8\fP [8]"
.br
.ti -1c
.RI "char \fBdata_8\fP [8]"
.br
.ti -1c
.RI "unsigned int \fBdata_u16\fP [4]"
.br
.ti -1c
.RI "int \fBdata_16\fP [4]"
.br
.ti -1c
.RI "unsigned long \fBdata_u32\fP [2]"
.br
.ti -1c
.RI "long \fBdata_32\fP [2]"
.br
.ti -1c
.RI "unsigned long long \fBdata_u64\fP"
.br
.ti -1c
.RI "long long \fBdata_64\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file util\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int data_16[4]"

.PP
Definition at line 27 of file util\&.h\&.
.SS "long data_32[2]"

.PP
Definition at line 29 of file util\&.h\&.
.SS "long long data_64"

.PP
Definition at line 31 of file util\&.h\&.
.SS "char data_8[8]"

.PP
Definition at line 25 of file util\&.h\&.
.SS "float data_fp[2]"

.PP
Definition at line 23 of file util\&.h\&.
.SS "unsigned int data_u16[4]"

.PP
Definition at line 26 of file util\&.h\&.
.SS "unsigned long data_u32[2]"

.PP
Definition at line 28 of file util\&.h\&.
.SS "unsigned long long data_u64"

.PP
Definition at line 30 of file util\&.h\&.
.SS "unsigned char data_u8[8]"

.PP
Definition at line 24 of file util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
