.TH "Calib_" 3 "Fri Nov 27 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calib_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cfg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIq\fP \fBscale\fP"
.br
.ti -1c
.RI "\fBIq\fP \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file cfg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBIq\fP offset"

.PP
Definition at line 34 of file cfg\&.h\&.
.SS "\fBIq\fP scale"

.PP
Definition at line 33 of file cfg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
