.TH "calibration_t" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
calibration_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "float \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float offset"

.PP
Definition at line 90 of file protocol\&.h\&.
.SS "float scale"

.PP
Definition at line 89 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
