.TH "CAN_Rx_" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_Rx_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <can\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBstatus\fP"
.br
.ti -1c
.RI "unsigned int \fBaddress\fP"
.br
.ti -1c
.RI "\fBgroup_64\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 132 of file can\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int address"

.PP
Definition at line 135 of file can\&.h\&.
.SS "\fBgroup_64\fP data"

.PP
Definition at line 136 of file can\&.h\&.
.SS "unsigned int status"

.PP
Definition at line 134 of file can\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
