.TH "CAN_TxBuffer_" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_TxBuffer_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <can\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCAN_TxBufferStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBgroup_64\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file can\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBgroup_64\fP data"

.PP
Definition at line 120 of file can\&.h\&.
.SS "\fBCAN_TxBufferStatus\fP status"

.PP
Definition at line 119 of file can\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
