.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/cfg.h" 3 "Wed Nov 25 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/cfg.h
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br
\fC#include 'iqmath\&.h'\fP
.br
\fC#include 'time\&.h'\fP
.br
\fC#include 'telem\&.h'\fP
.br
\fC#include 'safety\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBProductCode_\fP"
.br
.ti -1c
.RI "struct \fBCalib_\fP"
.br
.ti -1c
.RI "struct \fBCfg_\fP"
.br
.ti -1c
.RI "struct \fBLocalCfg_\fP"
.br
.ti -1c
.RI "struct \fBRemoteCfg_\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_CRC_OK\fP   0x80"
.br
.RI "#include 'flag\&.h' "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBProductCode_\fP \fBProductCode\fP"
.br
.ti -1c
.RI "typedef struct \fBCalib_\fP \fBCalib\fP"
.br
.ti -1c
.RI "typedef struct \fBCfg_\fP \fBCfg\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUInt16\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBUInt32\fP"
.br
.ti -1c
.RI "typedef struct \fBLocalCfg_\fP \fBLocalCfg\fP"
.br
.ti -1c
.RI "typedef struct \fBRemoteCfg_\fP \fBRemoteCfg\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCFG_init\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBCFG_getStatus\fP (void)"
.br
.ti -1c
.RI "int \fBCFG_configRangesOk\fP (void)"
.br
.ti -1c
.RI "int \fBCFG_checkRanges\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBCFG_getLocalCfgLen\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBCFG_getRemoteCfgLen\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBCFG_getReadonlyCfgLen\fP (void)"
.br
.ti -1c
.RI "unsigned char * \fBCFG_getReadonlyCfgAddr\fP (void)"
.br
.ti -1c
.RI "unsigned char * \fBCFG_getLocalCfgAddr\fP (void)"
.br
.ti -1c
.RI "unsigned char * \fBCFG_getRemoteCfgAddr\fP (void)"
.br
.ti -1c
.RI "void \fBCFG_productCode\fP (unsigned char *pDst)"
.br
.ti -1c
.RI "unsigned long \fBCFG_serialNumber\fP (void)"
.br
.ti -1c
.RI "unsigned long \fBCFG_canBaseId\fP (void)"
.br
.ti -1c
.RI "unsigned long \fBCFG_canBaud\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBCFG_configVersion\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_outVoltAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_outCurrAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_pvVoltAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_pvCurrAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_rail12VoltAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_flSetSenseAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_caseTmpAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_tmpCmpSenseAdcCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_mpptSamplePtDacCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_vinLimDacCal\fP (void)"
.br
.ti -1c
.RI "\fBCalib\fP \fBCFG_flTrimDacCal\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_thermRinf\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_thermBeta\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_maxVinOverVoc\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_overCurrSpSw\fP (void)"
.br
.ti -1c
.RI "\fBTELEM_SamplePeriod\fP \fBCFG_telemSamplePeriod\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBCFG_telemEnableBitfield\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_mpOcVoltRatio\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_bulkVolt\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_bulkTime\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_floatVolt\fP (void)"
.br
.ti -1c
.RI "float \fBCFG_tmpCmp\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCfg\fP \fBcfg\fP"
.br
.ti -1c
.RI "\fBLocalCfg\fP \fBCFG_localCfg\fP"
.br
.ti -1c
.RI "\fBRemoteCfg\fP \fBCFG_remoteCfg\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBCFG_toggleSwitchMode\fP"
.br
.ti -1c
.RI "float \fBCFG_outVoltCutoffOffset\fP"
.br
.ti -1c
.RI "float \fBCFG_outVoltCutoffScale\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_CRC_OK   0x80"

.PP
#include 'flag\&.h' 
.PP
Definition at line 22 of file cfg\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBCalib_\fP \fBCalib\fP"

.SS "typedef struct \fBCfg_\fP \fBCfg\fP"

.SS "typedef struct \fBLocalCfg_\fP \fBLocalCfg\fP"

.SS "typedef struct \fBProductCode_\fP \fBProductCode\fP"

.SS "typedef struct \fBRemoteCfg_\fP \fBRemoteCfg\fP"

.SS "typedef unsigned int \fBUInt16\fP"

.PP
Definition at line 89 of file cfg\&.h\&.
.SS "typedef unsigned long \fBUInt32\fP"

.PP
Definition at line 90 of file cfg\&.h\&.
.SH "Function Documentation"
.PP 
.SS "float CFG_bulkTime (void)"

.SS "float CFG_bulkVolt (void)"

.SS "unsigned long CFG_canBaseId (void)"

.SS "unsigned long CFG_canBaud (void)"

.SS "\fBCalib\fP CFG_caseTmpAdcCal (void)"

.SS "int CFG_checkRanges (void)"

.PP
Definition at line 180 of file cfg\&.c\&.
.SS "int CFG_configRangesOk (void)"

.PP
Definition at line 228 of file cfg\&.c\&.
.SS "unsigned int CFG_configVersion (void)"

.SS "float CFG_floatVolt (void)"

.SS "\fBCalib\fP CFG_flSetSenseAdcCal (void)"

.SS "\fBCalib\fP CFG_flTrimDacCal (void)"

.SS "unsigned char* CFG_getLocalCfgAddr (void)"

.PP
Definition at line 248 of file cfg\&.c\&.
.SS "unsigned int CFG_getLocalCfgLen (void)"

.PP
Definition at line 233 of file cfg\&.c\&.
.SS "unsigned char* CFG_getReadonlyCfgAddr (void)"

.PP
Definition at line 258 of file cfg\&.c\&.
.SS "unsigned int CFG_getReadonlyCfgLen (void)"

.PP
Definition at line 243 of file cfg\&.c\&.
.SS "unsigned char* CFG_getRemoteCfgAddr (void)"

.PP
Definition at line 253 of file cfg\&.c\&.
.SS "unsigned int CFG_getRemoteCfgLen (void)"

.PP
Definition at line 238 of file cfg\&.c\&.
.SS "unsigned char CFG_getStatus (void)"

.PP
Definition at line 223 of file cfg\&.c\&.
.SS "void CFG_init (void)"

.PP
Definition at line 121 of file cfg\&.c\&.
.SS "float CFG_maxVinOverVoc (void)"

.SS "float CFG_mpOcVoltRatio (void)"

.SS "\fBCalib\fP CFG_mpptSamplePtDacCal (void)"

.SS "\fBCalib\fP CFG_outCurrAdcCal (void)"

.SS "\fBCalib\fP CFG_outVoltAdcCal (void)"

.SS "float CFG_overCurrSpSw (void)"

.SS "void CFG_productCode (unsigned char * pDst)"

.SS "\fBCalib\fP CFG_pvCurrAdcCal (void)"

.SS "\fBCalib\fP CFG_pvVoltAdcCal (void)"

.SS "\fBCalib\fP CFG_rail12VoltAdcCal (void)"

.SS "unsigned long CFG_serialNumber (void)"

.SS "unsigned int CFG_telemEnableBitfield (void)"

.SS "\fBTELEM_SamplePeriod\fP CFG_telemSamplePeriod (void)"

.SS "float CFG_thermBeta (void)"

.SS "float CFG_thermRinf (void)"

.SS "float CFG_tmpCmp (void)"

.SS "\fBCalib\fP CFG_tmpCmpSenseAdcCal (void)"

.SS "\fBCalib\fP CFG_vinLimDacCal (void)"

.SH "Variable Documentation"
.PP 
.SS "\fBCfg\fP cfg\fC [extern]\fP"

.PP
Definition at line 115 of file cfg\&.c\&.
.SS "\fBLocalCfg\fP CFG_localCfg\fC [extern]\fP"

.PP
Definition at line 24 of file cfg\&.c\&.
.SS "float CFG_outVoltCutoffOffset\fC [extern]\fP"

.PP
Definition at line 118 of file cfg\&.c\&.
.SS "float CFG_outVoltCutoffScale\fC [extern]\fP"

.PP
Definition at line 119 of file cfg\&.c\&.
.SS "\fBRemoteCfg\fP CFG_remoteCfg\fC [extern]\fP"

.PP
Definition at line 61 of file cfg\&.c\&.
.SS "\fBUInt16\fP CFG_toggleSwitchMode\fC [extern]\fP"

.PP
Definition at line 117 of file cfg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
