.TH "commsConfig_t" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commsConfig_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBmodBusAddress\fP"
.br
.ti -1c
.RI "unsigned char \fBcanBaudRate\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBcanBusID\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBisSlave\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fB__pad0__\fP: 16"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 143 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint16_t\fP __pad0__"

.PP
Definition at line 148 of file protocol\&.h\&.
.SS "unsigned char canBaudRate"

.PP
Definition at line 145 of file protocol\&.h\&.
.SS "\fBuint16_t\fP canBusID"

.PP
Definition at line 146 of file protocol\&.h\&.
.SS "\fBuint16_t\fP isSlave"

.PP
Definition at line 147 of file protocol\&.h\&.
.SS "unsigned char modBusAddress"

.PP
Definition at line 144 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
