.TH "Comms_" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comms_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBP2p\fP \fBp2p\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file comms\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBP2p\fP p2p"

.PP
Definition at line 93 of file comms\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
