.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/ctrl.h" 3 "Wed Nov 25 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/ctrl.h
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCTRL_SLOW_PERIOD_MS\fP   100"
.br
.ti -1c
.RI "#define \fBCTRL_BULK_HYSTERISIS_MS\fP   2000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCTRL_init\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_setFltrimParams_old\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_setFltrimParams_new\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_setOutVoltCmd\fP (float outVoltCmd)"
.br
.ti -1c
.RI "float \fBCTRL_getOutVoltCmd\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_calcOutVoltSetpoints\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_enableOutput\fP (int enable)"
.br
.ti -1c
.RI "int \fBCTRL_isOutputEnabled\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_tick\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_checkBulkFloat\fP ()"
.br
.ti -1c
.RI "int \fBCTRL_setpointIsBulk\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_controlSyncRect\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_vmpHigh\fP ()"
.br
.ti -1c
.RI "unsigned char \fBCTRL_getStatus\fP ()"
.br
.ti -1c
.RI "void \fBCTRL_temp\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CTRL_BULK_HYSTERISIS_MS   2000"

.PP
Definition at line 18 of file ctrl\&.h\&.
.SS "#define CTRL_SLOW_PERIOD_MS   100"

.PP
Definition at line 17 of file ctrl\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void CTRL_calcOutVoltSetpoints ()"

.PP
Definition at line 277 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_checkBulkFloat ()"

.PP
Definition at line 850 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_controlSyncRect ()"

.SS "void CTRL_enableOutput (int enable)"

.PP
Definition at line 369 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "float CTRL_getOutVoltCmd ()"

.PP
Definition at line 271 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "unsigned char CTRL_getStatus ()"

.PP
Definition at line 842 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_init ()"

.PP
Definition at line 167 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "int CTRL_isOutputEnabled ()"

.PP
Definition at line 375 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_setFltrimParams_new ()"

.PP
Definition at line 246 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_setFltrimParams_old ()"

.PP
Definition at line 254 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_setOutVoltCmd (float outVoltCmd)"

.PP
Definition at line 262 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "int CTRL_setpointIsBulk ()"

.PP
Definition at line 926 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_temp ()"

.SS "void CTRL_tick ()"

.PP
Definition at line 391 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SS "void CTRL_vmpHigh ()"

.PP
Definition at line 822 of file ctrl (Конфликтующая копия с компьютера Nsel 2020\-08\-03)\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
