.TH "eventFlags_t" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eventFlags_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBsystemPower\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBlowOutVoltWarn\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBlowOutVoltFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBlowOutVoltGenSet\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighOutVoltFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighOutCurrentFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighDischargeCurrentFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighBatteryTempFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBinputBreakerOpen\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBoutputBreakerOpen\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBtempSensorFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBnegativePVCurrentSutdown\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighPVCurrentShutdown\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighPVVoltShutdown\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighOutCurrentShutdown\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighOutVoltShutdown\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBhighHeatSinkTemp\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBfanFault\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBlogFull\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBsolarPanelMissing\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBconfigValueOutOfRange\fP: 1"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fB__pad0__\fP: 11"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "\fBuint32_t\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "\fBuint32_t\fP __pad0__"

.PP
Definition at line 31 of file protocol\&.h\&.
.SS "\fBuint32_t\fP configValueOutOfRange"

.PP
Definition at line 30 of file protocol\&.h\&.
.SS "\fBuint32_t\fP fanFault"

.PP
Definition at line 27 of file protocol\&.h\&.
.SS "\fBuint32_t\fP flags"

.PP
Definition at line 33 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highBatteryTempFault"

.PP
Definition at line 17 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highDischargeCurrentFault"

.PP
Definition at line 16 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highHeatSinkTemp"

.PP
Definition at line 26 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highOutCurrentFault"

.PP
Definition at line 15 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highOutCurrentShutdown"

.PP
Definition at line 24 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highOutVoltFault"

.PP
Definition at line 14 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highOutVoltShutdown"

.PP
Definition at line 25 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highPVCurrentShutdown"

.PP
Definition at line 22 of file protocol\&.h\&.
.SS "\fBuint32_t\fP highPVVoltShutdown"

.PP
Definition at line 23 of file protocol\&.h\&.
.SS "\fBuint32_t\fP inputBreakerOpen"

.PP
Definition at line 18 of file protocol\&.h\&.
.SS "\fBuint32_t\fP logFull"

.PP
Definition at line 28 of file protocol\&.h\&.
.SS "\fBuint32_t\fP lowOutVoltFault"

.PP
Definition at line 12 of file protocol\&.h\&.
.SS "\fBuint32_t\fP lowOutVoltGenSet"

.PP
Definition at line 13 of file protocol\&.h\&.
.SS "\fBuint32_t\fP lowOutVoltWarn"

.PP
Definition at line 11 of file protocol\&.h\&.
.SS "\fBuint32_t\fP negativePVCurrentSutdown"

.PP
Definition at line 21 of file protocol\&.h\&.
.SS "\fBuint32_t\fP outputBreakerOpen"

.PP
Definition at line 19 of file protocol\&.h\&.
.SS "\fBuint32_t\fP solarPanelMissing"

.PP
Definition at line 29 of file protocol\&.h\&.
.SS "\fBuint32_t\fP systemPower"

.PP
Definition at line 10 of file protocol\&.h\&.
.SS "\fBuint32_t\fP tempSensorFault"

.PP
Definition at line 20 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
