.TH "eventParams_missing_t" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eventParams_missing_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16_t\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fB__pad0__\fP: 16"
.br
.ti -1c
.RI "float \fBtriggerVal\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBcheckTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 136 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint16_t\fP __pad0__"

.PP
Definition at line 138 of file protocol\&.h\&.
.SS "\fBuint32_t\fP checkTime"

.PP
Definition at line 140 of file protocol\&.h\&.
.SS "\fBuint16_t\fP mode"

.PP
Definition at line 137 of file protocol\&.h\&.
.SS "float triggerVal"

.PP
Definition at line 139 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
