.TH "factoryConfig_t" 3 "Fri Nov 27 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factoryConfig_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char \fBproductID\fP [8]"
.br
.ti -1c
.RI "   char \fBserialNumber\fP [8]"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBoutVoltAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBoutCurrentAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBpvVoltAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBpvCurrentAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBrail12VoltAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBfloatSetSenseAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBpwmErrorMinusAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBtmpCmpSenseAdcCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBmpptSamplePointDacCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBvinLimDacCal\fP"
.br
.ti -1c
.RI "   \fBcalibration_t\fP \fBfloatTrimDacCal\fP"
.br
.ti -1c
.RI "   float \fBthermRinf\fP"
.br
.ti -1c
.RI "   float \fBthermBeta\fP"
.br
.ti -1c
.RI "   float \fBoverCurrentSetPoint\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned char \fBbytes\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "unsigned char bytes[1]"

.PP
Definition at line 112 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP floatSetSenseAdcCal"

.PP
Definition at line 102 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP floatTrimDacCal"

.PP
Definition at line 107 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP mpptSamplePointDacCal"

.PP
Definition at line 105 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP outCurrentAdcCal"

.PP
Definition at line 98 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP outVoltAdcCal"

.PP
Definition at line 97 of file protocol\&.h\&.
.SS "float overCurrentSetPoint"

.PP
Definition at line 110 of file protocol\&.h\&.
.SS "char productID[8]"

.PP
Definition at line 95 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP pvCurrentAdcCal"

.PP
Definition at line 100 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP pvVoltAdcCal"

.PP
Definition at line 99 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP pwmErrorMinusAdcCal"

.PP
Definition at line 103 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP rail12VoltAdcCal"

.PP
Definition at line 101 of file protocol\&.h\&.
.SS "char serialNumber[8]"

.PP
Definition at line 96 of file protocol\&.h\&.
.SS "float thermBeta"

.PP
Definition at line 109 of file protocol\&.h\&.
.SS "float thermRinf"

.PP
Definition at line 108 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP tmpCmpSenseAdcCal"

.PP
Definition at line 104 of file protocol\&.h\&.
.SS "\fBcalibration_t\fP vinLimDacCal"

.PP
Definition at line 106 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
