.TH "FlagCfgHold_" 3 "Wed Nov 25 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlagCfgHold_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flag\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFLAG_Mode\fP \fBmode\fP"
.br
.ti -1c
.RI "float \fBtriggerVal\fP"
.br
.ti -1c
.RI "float \fBresetVal\fP"
.br
.ti -1c
.RI "\fBTimeShort\fP \fBhystTime\fP"
.br
.ti -1c
.RI "\fBTimeShort\fP \fBholdTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file flag\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBTimeShort\fP holdTime"

.PP
Definition at line 50 of file flag\&.h\&.
.SS "\fBTimeShort\fP hystTime"

.PP
Definition at line 49 of file flag\&.h\&.
.SS "\fBFLAG_Mode\fP mode"

.PP
Definition at line 46 of file flag\&.h\&.
.SS "float resetVal"

.PP
Definition at line 48 of file flag\&.h\&.
.SS "float triggerVal"

.PP
Definition at line 47 of file flag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
