.TH "FlagCfgSched_" 3 "Wed Nov 25 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlagCfgSched_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flag\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFLAG_Mode\fP \fBmode\fP"
.br
.ti -1c
.RI "float \fBtriggerVal\fP"
.br
.ti -1c
.RI "\fBTimeShort\fP \fBcheckTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file flag\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBTimeShort\fP checkTime"

.PP
Definition at line 58 of file flag\&.h\&.
.SS "\fBFLAG_Mode\fP mode"

.PP
Definition at line 56 of file flag\&.h\&.
.SS "float triggerVal"

.PP
Definition at line 57 of file flag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
