.TH "Flag_" 3 "Fri Nov 27 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flag_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBbuffer\fP [\fBFLAG_CODE_NUM\fP *\fBFLAG_BUFFER_ENTRY_SIZE\fP]"
.br
.ti -1c
.RI "unsigned long \fBcurrentAddr\fP"
.br
.ti -1c
.RI "unsigned long \fBactiveSectorAddr\fP"
.br
.ti -1c
.RI "unsigned int \fBactiveSectorNum\fP"
.br
.ti -1c
.RI "\fBFlagBitfield\fP \fBflagBitfield\fP"
.br
.ti -1c
.RI "\fBFlagBitfield\fP \fBflagBitfieldRelay\fP"
.br
.ti -1c
.RI "int \fBisReadyToCheck\fP"
.br
.ti -1c
.RI "int \fBisReadyToWrite\fP"
.br
.ti -1c
.RI "int \fBisErasing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file flag\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long activeSectorAddr"

.PP
Definition at line 40 of file flag\&.c\&.
.SS "unsigned int activeSectorNum"

.PP
Definition at line 41 of file flag\&.c\&.
.SS "unsigned char buffer[\fBFLAG_CODE_NUM\fP *\fBFLAG_BUFFER_ENTRY_SIZE\fP]"

.PP
Definition at line 38 of file flag\&.c\&.
.SS "unsigned long currentAddr"

.PP
Definition at line 39 of file flag\&.c\&.
.SS "\fBFlagBitfield\fP flagBitfield"

.PP
Definition at line 42 of file flag\&.c\&.
.SS "\fBFlagBitfield\fP flagBitfieldRelay"

.PP
Definition at line 43 of file flag\&.c\&.
.SS "int isErasing"

.PP
Definition at line 46 of file flag\&.c\&.
.SS "int isReadyToCheck"

.PP
Definition at line 44 of file flag\&.c\&.
.SS "int isReadyToWrite"

.PP
Definition at line 45 of file flag\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
