.TH "FlagState_" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlagState_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flag\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFLAG_State\fP \fBcurrentState\fP"
.br
.ti -1c
.RI "\fBIq\fP \fBcurrentVal\fP"
.br
.ti -1c
.RI "\fBIq\fP \fBtriggerVal\fP"
.br
.ti -1c
.RI "\fBIq\fP \fBresetVal\fP"
.br
.ti -1c
.RI "\fBTime\fP \fBhystStartTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file flag\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBFLAG_State\fP currentState"

.PP
Definition at line 101 of file flag\&.h\&.
.SS "\fBIq\fP currentVal"

.PP
Definition at line 102 of file flag\&.h\&.
.SS "\fBTime\fP hystStartTime"

.PP
Definition at line 105 of file flag\&.h\&.
.SS "\fBIq\fP resetVal"

.PP
Definition at line 104 of file flag\&.h\&.
.SS "\fBIq\fP triggerVal"

.PP
Definition at line 103 of file flag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
