.TH "Flash_" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flash_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile \fBFlashMode\fP \fBmode\fP"
.br
.ti -1c
.RI "unsigned long \fBcurrentAddr\fP"
.br
.ti -1c
.RI "unsigned long \fBlenRem\fP"
.br
.ti -1c
.RI "int \fBhasWritten\fP"
.br
.ti -1c
.RI "\fBCircBuffer\fP \fBbuffer\fP"
.br
.ti -1c
.RI "void(* \fBpCallback\fP )(int)"
.br
.ti -1c
.RI "unsigned char \fBbufferStore\fP [\fBFLASH_BUFFER_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file flash\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBCircBuffer\fP buffer"

.PP
Definition at line 41 of file flash\&.c\&.
.SS "unsigned char bufferStore[\fBFLASH_BUFFER_SIZE\fP]"

.PP
Definition at line 43 of file flash\&.c\&.
.SS "unsigned long currentAddr"

.PP
Definition at line 38 of file flash\&.c\&.
.SS "int hasWritten"

.PP
Definition at line 40 of file flash\&.c\&.
.SS "unsigned long lenRem"

.PP
Definition at line 39 of file flash\&.c\&.
.SS "volatile \fBFlashMode\fP mode"

.PP
Definition at line 37 of file flash\&.c\&.
.SS "void(* pCallback) (int)"

.PP
Definition at line 42 of file flash\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
