.TH "groupFAN" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupFAN \- FAN
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBIO_setFanDutyCycle\fP (unsigned int fanDuty)"
.br
.RI "Limits fanDuty\&. "
.ti -1c
.RI "void \fBIO_fanDrvPWM\fP ()"
.br
.RI "Program PWM for FAN\&. "
.ti -1c
.RI "void \fBIO_fanSenseSpeed\fP ()"
.br
.RI "program counter of edges "
.ti -1c
.RI "void \fBIO_fanSetSpeed\fP ()"
.br
.RI "High level logic for FAN\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
            FAN                                                     high level logic       limit fanDuty

        mainMSP.c:mainMSPloop()->sch.c:SCH_runActiveTasks()->io.c:IO_fanSetSpeed->io.c:IO_setFanDutyCycle( unsigned int fanDuty);

mainMSP.c:TIM3_IRQHandler(void)->PWM.c:PWM_isr(void)->io.c:IO_fanSenseSpeed(void);

  mainMSP.c:mainMSPloop()->sch.c:SCH_runActiveTasks()->io.c:IO_fanDrvPWM(void);

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "void IO_fanDrvPWM (void)"

.PP
Program PWM for FAN\&. 
.PP
Definition at line 341 of file io\&.c\&.
.SS "void IO_fanSenseSpeed (void)"

.PP
program counter of edges 
.PP
\fBTodo\fP
.RS 4
make fanFBCount1 like fanFBCount2
.RE
.PP
.PP
FAN speed: curFanFBCount1, curFanFBCount2
.PP
Speed analized in \fBIO_fanSetSpeed()\fP
.PP
This is called at the PWM frequency which is about every 512us as of revision 133\&. Rated fan speed is 4300RPM which is about 6\&.5 ms between falling edges, or 13ms for a full rotation of the fan\&. This corresponds to fanFBPeriod of about 0x0C The safety cutoff for fanFBPeriod is set to FAN_PERIOD_MAXIMUM = 0x14 
.PP
Definition at line 378 of file io\&.c\&.
.SS "void IO_fanSetSpeed (void)"

.PP
High level logic for FAN\&. Run by scheduler every 2 seconds 
.PP
Definition at line 414 of file io\&.c\&.
.SS "void IO_setFanDutyCycle (unsigned int fanDuty)"

.PP
Limits fanDuty\&. 
.PP
Definition at line 192 of file io\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
