.TH "hware_info_" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hware_info_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <variant\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBdevice_id\fP"
.br
.ti -1c
.RI "unsigned char \fBhardware_version\fP"
.br
.ti -1c
.RI "unsigned char \fBmodel_id\fP"
.br
.ti -1c
.RI "unsigned char \fBbootloader_version\fP"
.br
.ti -1c
.RI "unsigned char \fBunallocated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file variant\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char bootloader_version"

.PP
Definition at line 41 of file variant\&.h\&.
.SS "unsigned long device_id"

.PP
Definition at line 38 of file variant\&.h\&.
.SS "unsigned char hardware_version"

.PP
Definition at line 39 of file variant\&.h\&.
.SS "unsigned char model_id"

.PP
Definition at line 40 of file variant\&.h\&.
.SS "unsigned char unallocated"

.PP
Definition at line 42 of file variant\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
