.TH "IntegralMeas_" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntegralMeas_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <meas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIqLong\fP \fBval\fP"
.br
.ti -1c
.RI "float \fBbase\fP"
.br
.ti -1c
.RI "float \fBvalReal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 103 of file meas\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float base"

.PP
Definition at line 106 of file meas\&.h\&.
.SS "\fBIqLong\fP val"

.PP
Definition at line 105 of file meas\&.h\&.
.SS "float valReal"

.PP
Definition at line 107 of file meas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
