.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/inttype.h" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/inttype.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBuint32_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBuint16_t\fP"

.PP
Definition at line 2 of file inttype\&.h\&.
.SS "typedef unsigned long \fBuint32_t\fP"

.PP
Definition at line 3 of file inttype\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
