.TH "D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/io.c" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/io.c \- Discrete I / O control\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Stm32f3xx\&.h'\fP
.br
\fC#include 'variant\&.h'\fP
.br
\fC#include 'io\&.h'\fP
.br
\fC#include 'ctrl\&.h'\fP
.br
\fC#include 'flag\&.h'\fP
.br
\fC#include 'meas\&.h'\fP
.br
\fC#include 'safety\&.h'\fP
.br
\fC#include 'pwm\&.h'\fP
.br
\fC#include 'comms\&.h'\fP
.br
\fC#include 'cfg\&.h'\fP
.br
\fC#include 'adc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIO_FAN_PWM_PERIOD\fP   10"
.br
.ti -1c
.RI "#define \fBIO_HEATSINK_TEMP_FAN_THRESHOLD\fP   31\&.0"
.br
.ti -1c
.RI "#define \fBIO_HEATSINK_TEMP_FAN_RESET\fP   10\&.0"
.br
.ti -1c
.RI "#define \fBIO_FAN_MINIMUM_CURRENT\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBIO_FAN_COUNT_TIMEOUT\fP   100"
.br
.ti -1c
.RI "#define \fBIO_SYNCRECT_UPPER_THRESHOLD\fP   (10\&.0 / \fBMEAS_OUTCURR_BASE\fP)"
.br
.ti -1c
.RI "#define \fBIO_SYNCRECT_LOWER_THRESHOLD\fP   (4\&.0 / \fBMEAS_OUTCURR_BASE\fP)"
.br
.ti -1c
.RI "#define \fBIO_SYNCRECT_TIME_HYST_TICKS\fP   (unsigned long)( 1\&.0 * 1000000\&.0 / (float)\fBPWM_PERIOD_US\fP )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBIO_init\fP (void)"
.br
.ti -1c
.RI "void \fBIO_setFanDutyCycle\fP (unsigned int fanDuty)"
.br
.RI "Limits fanDuty\&. "
.ti -1c
.RI "int \fBIO_getOnOff\fP ()"
.br
.RI "Just returns the state of the input\&. "
.ti -1c
.RI "int \fBIO_getGroundFault\fP ()"
.br
.RI "Just returns the state of the input\&. "
.ti -1c
.RI "int \fBIO_getDigitalTemp\fP ()"
.br
.RI "Just returns the state of the input\&. "
.ti -1c
.RI "int \fBIO_getIsSlave\fP ()"
.br
.RI "not real input, return( (int)( CFG_localCfg\&.isSlave ) ); "
.ti -1c
.RI "void \fBIO_setRelay\fP (unsigned long long bitfield)"
.br
.RI "just on/off relay "
.ti -1c
.RI "void \fBIO_fanDrvPWM\fP ()"
.br
.RI "Program PWM for FAN\&. "
.ti -1c
.RI "void \fBIO_fanSenseSpeed\fP ()"
.br
.RI "program counter of edges "
.ti -1c
.RI "void \fBIO_fanSetSpeed\fP ()"
.br
.RI "High level logic for FAN\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBfanPWMCounter\fP =0"
.br
.ti -1c
.RI "unsigned int \fBfanDutyCompare\fP"
.br
.ti -1c
.RI "floatValue_t \fBcalculatedValue\fP"
.br
.ti -1c
.RI "unsigned int \fBIO_pwmEnabled\fP"
.br
.ti -1c
.RI "long \fBTicksUntilHiSideAllowed\fP"
.br
.ti -1c
.RI "float \fBheatsinkTempFanHysThresh\fP = \fBIO_HEATSINK_TEMP_FAN_THRESHOLD\fP"
.br
.ti -1c
.RI "int \fBfanFBCount1\fP"
.br
.ti -1c
.RI "int \fBfanFBCount2\fP"
.br
.ti -1c
.RI "int \fBprevFan2State\fP"
.br
.ti -1c
.RI "int \fBfanFBTransition1\fP"
.br
.ti -1c
.RI "int \fBfanFBTransition2\fP"
.br
.ti -1c
.RI "unsigned int \fBfanDriven\fP"
.br
.ti -1c
.RI "unsigned int \fBfanShutdown\fP"
.br
.ti -1c
.RI "unsigned int \fBfanRestartTimer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Discrete I / O control\&. 


.PP
 File: \fBio\&.c\fP Project: CY CoolMax MPPT Device: MSP430F247 Author: Monte MacDiarmid, Tritium Pty Ltd\&. Description: History: 
.SS "2010-07-07: original"
Schematic Digital Input Output
.PP
CASETMP thermistor, no in this file
.PP
ON_OFF_GFD 
.PP
.nf
      io.c:IO_getGroundFault()

                ctrl.c:CTRL_tick()->io.c:IO_getGroundFault()

                RDD !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! set with delay disablePWM according to  GroundFault: J10 on PWRboard

.fi
.PP
.PP
RELAY_1_EN
.PP
RELAY_2_EN 
.PP
.nf
      mainMSP.c:mainMSPloop()->sch.c:SCH_runActiveTasks()->
                FLAG_checkAndWrite()->FLAG_checkAllFlags->io.c:IO_setRelay

.fi
.PP
.PP
TMPCMP Digital 
.PP
.nf
   io.c: int IO_getDigitalTemp()

   temp.c:TEMP_init()->io.c: int IO_getDigitalTemp()

           pwm.c:PWM_isr()->temp.c:TEMP_tick()->io.c: int IO_getDigitalTemp()

.fi
.PP
.PP
ONOFF/SLAVE# 
.PP
.nf
    pwm.c:PWM_isr->cntrl.c:CTRL_tick()->io.c:int IO_getOnOff() 

.fi
.PP
.PP
In \fBio\&.c\fP: 
.PP
.nf
    IO_getIsSlave

            FAN                                                     high level logic       limit fanDuty

            mainMSP.c:mainMSPloop()->sch.c:SCH_runActiveTasks()->io.c:IO_fanSetSpeed->io.c:IO_setFanDutyCycle( unsigned int fanDuty);

    mainMSP.c:TIM3_IRQHandler(void)->PWM.c:PWM_isr(void)->io.c:IO_fanSenseSpeed(void);

      mainMSP.c:mainMSPloop()->sch.c:SCH_runActiveTasks()->io.c:IO_fanDrvPWM(void);

.fi
.PP
 
.PP
Definition in file \fBio\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define IO_FAN_COUNT_TIMEOUT   100"

.PP
Definition at line 100 of file io\&.c\&.
.SS "#define IO_FAN_MINIMUM_CURRENT   0\&.0"

.PP
Definition at line 95 of file io\&.c\&.
.SS "#define IO_FAN_PWM_PERIOD   10"

.PP
Definition at line 84 of file io\&.c\&.
.SS "#define IO_HEATSINK_TEMP_FAN_RESET   10\&.0"

.PP
Definition at line 90 of file io\&.c\&.
.SS "#define IO_HEATSINK_TEMP_FAN_THRESHOLD   31\&.0"

.PP
Definition at line 89 of file io\&.c\&.
.SS "#define IO_SYNCRECT_LOWER_THRESHOLD   (4\&.0 / \fBMEAS_OUTCURR_BASE\fP)"

.PP
Definition at line 103 of file io\&.c\&.
.SS "#define IO_SYNCRECT_TIME_HYST_TICKS   (unsigned long)( 1\&.0 * 1000000\&.0 / (float)\fBPWM_PERIOD_US\fP )"

.PP
Definition at line 105 of file io\&.c\&.
.SS "#define IO_SYNCRECT_UPPER_THRESHOLD   (10\&.0 / \fBMEAS_OUTCURR_BASE\fP)"

.PP
Definition at line 102 of file io\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int IO_getGroundFault (void)"

.PP
Just returns the state of the input\&. set with delay disablePWM according to GroundFault: J10 on PWRboard 
.PP
Definition at line 219 of file io\&.c\&.
.SS "int IO_getIsSlave (void)"

.PP
not real input, return( (int)( CFG_localCfg\&.isSlave ) ); 
.PP
Definition at line 301 of file io\&.c\&.
.SS "int IO_getOnOff (void)"

.PP
Just returns the state of the input\&. \fBpwm\&.c\fP:PWM_isr->cntrl\&.c:\fBCTRL_tick()\fP->\fBio\&.c\fP:int \fBIO_getOnOff()\fP 
.PP
Definition at line 208 of file io\&.c\&.
.SS "void IO_init (void)"

.PP
Definition at line 128 of file io\&.c\&.
.SS "void IO_setRelay (unsigned long long bitfield)"

.PP
just on/off relay \fBmainMSP\&.c\fP:\fBmainMSPloop()\fP->\fBsch\&.c\fP:\fBSCH_runActiveTasks()\fP-> \fBFLAG_checkAndWrite()\fP->FLAG_checkAllFlags->\fBio\&.c\fP:IO_setRelay
.PP
\fBTodo\fP
.RS 4
2 relay
.RE
.PP

.PP
Definition at line 320 of file io\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "floatValue_t calculatedValue\fC [extern]\fP"

.SS "unsigned int fanDriven"

.PP
Definition at line 124 of file io\&.c\&.
.SS "unsigned int fanDutyCompare"

.PP
Definition at line 109 of file io\&.c\&.
.SS "int fanFBCount1"

.PP
Definition at line 117 of file io\&.c\&.
.SS "int fanFBCount2"

.PP
Definition at line 119 of file io\&.c\&.
.SS "int fanFBTransition1"

.PP
Definition at line 122 of file io\&.c\&.
.SS "int fanFBTransition2"

.PP
Definition at line 123 of file io\&.c\&.
.SS "unsigned int fanPWMCounter =0"

.PP
Definition at line 108 of file io\&.c\&.
.SS "unsigned int fanRestartTimer"

.PP
Definition at line 126 of file io\&.c\&.
.SS "unsigned int fanShutdown"

.PP
Definition at line 125 of file io\&.c\&.
.SS "float heatsinkTempFanHysThresh = \fBIO_HEATSINK_TEMP_FAN_THRESHOLD\fP"

.PP
Definition at line 115 of file io\&.c\&.
.SS "unsigned int IO_pwmEnabled"

.PP
Definition at line 113 of file io\&.c\&.
.SS "int prevFan2State"

.PP
Definition at line 120 of file io\&.c\&.
.SS "long TicksUntilHiSideAllowed"

.PP
Definition at line 114 of file io\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
