.TH "D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/iqmath.h" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/iqmath.h
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIQ_Q\fP   12"
.br
.ti -1c
.RI "#define \fBIQ_K\fP   (1 << (\fBIQ_Q\fP\-1))"
.br
.ti -1c
.RI "#define \fBIQ_MIN\fP   0x8000"
.br
.ti -1c
.RI "#define \fBIQ_MAX\fP   0x7FFF"
.br
.ti -1c
.RI "#define \fBIQ_cnst\fP(A)   ( (\fBIq\fP) ((A) * 4096\&.0) )"
.br
.ti -1c
.RI "#define \fBIQ_abs\fP(A)   ( ((A)<0)?(\-(A)):(A) )"
.br
.ti -1c
.RI "#define \fBIQ_sign\fP(A)   ( ((A)==0)?(0):(((A)<0)?(\-1):(1)) )"
.br
.ti -1c
.RI "#define \fBIQ_min\fP(A,  B)   ( ((A)<(B))?(A):(B) )"
.br
.ti -1c
.RI "#define \fBIQ_max\fP(A,  B)   ( ((A)>(B))?(A):(B) )"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBIq\fP"
.br
.ti -1c
.RI "typedef long int \fBIqLong\fP"
.br
.ti -1c
.RI "typedef long int \fBIq24Long\fP"
.br
.ti -1c
.RI "typedef long long int \fBIq24LongLong\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIq\fP \fBIQ_mpy\fP (\fBIq\fP a, \fBIq\fP b)"
.br
.RI "#include <msp430x24x\&.h> "
.ti -1c
.RI "\fBIq24Long\fP \fBIQ_mpyTo24\fP (\fBIq\fP a, \fBIq\fP b)"
.br
.ti -1c
.RI "\fBIq\fP \fBIQ_div\fP (\fBIq\fP a, \fBIq\fP b)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IQ_abs(A)   ( ((A)<0)?(\-(A)):(A) )"

.PP
Definition at line 30 of file iqmath\&.h\&.
.SS "#define IQ_cnst(A)   ( (\fBIq\fP) ((A) * 4096\&.0) )"

.PP
Definition at line 28 of file iqmath\&.h\&.
.SS "#define IQ_K   (1 << (\fBIQ_Q\fP\-1))"

.PP
Definition at line 18 of file iqmath\&.h\&.
.SS "#define IQ_MAX   0x7FFF"

.PP
Definition at line 26 of file iqmath\&.h\&.
.SS "#define IQ_max(A, B)   ( ((A)>(B))?(A):(B) )"

.PP
Definition at line 33 of file iqmath\&.h\&.
.SS "#define IQ_MIN   0x8000"

.PP
Definition at line 25 of file iqmath\&.h\&.
.SS "#define IQ_min(A, B)   ( ((A)<(B))?(A):(B) )"

.PP
Definition at line 32 of file iqmath\&.h\&.
.SS "#define IQ_Q   12"

.PP
Definition at line 17 of file iqmath\&.h\&.
.SS "#define IQ_sign(A)   ( ((A)==0)?(0):(((A)<0)?(\-1):(1)) )"

.PP
Definition at line 31 of file iqmath\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBIq\fP"

.PP
Definition at line 20 of file iqmath\&.h\&.
.SS "typedef long int \fBIq24Long\fP"

.PP
Definition at line 22 of file iqmath\&.h\&.
.SS "typedef long long int \fBIq24LongLong\fP"

.PP
Definition at line 23 of file iqmath\&.h\&.
.SS "typedef long int \fBIqLong\fP"

.PP
Definition at line 21 of file iqmath\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBIq\fP IQ_div (\fBIq\fP a, \fBIq\fP b)"

.PP
Definition at line 65 of file iqmath\&.c\&.
.SS "\fBIq\fP IQ_mpy (\fBIq\fP a, \fBIq\fP b)"

.PP
#include <msp430x24x\&.h> 
.PP
Definition at line 17 of file iqmath\&.c\&.
.SS "\fBIq24Long\fP IQ_mpyTo24 (\fBIq\fP a, \fBIq\fP b)"

.PP
Definition at line 53 of file iqmath\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
