.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/lcd.h" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/lcd.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDSP28_DATA_TYPES\fP"
.br
.ti -1c
.RI "#define \fBLCD_PERIOD_MS\fP   500"
.br
.ti -1c
.RI "#define \fBCOMMSTIMEOUT\fP   5"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBint8\fP"
.br
.ti -1c
.RI "typedef int \fBint16\fP"
.br
.ti -1c
.RI "typedef long \fBint32\fP"
.br
.ti -1c
.RI "typedef long long \fBint64\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBUint8\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUint16\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBUint32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBUint64\fP"
.br
.ti -1c
.RI "typedef float \fBfloat32\fP"
.br
.ti -1c
.RI "typedef long double \fBfloat64\fP"
.br
.ti -1c
.RI "typedef enum \fBlcd_CfgState_\fP \fBlcd_CfgState\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlcd_CfgState_\fP { \fBLCDCFG_STATE_CFG_IDLE\fP = 0, \fBLCDCFG_STATE_ERASE\fP, \fBLCDCFG_STATE_WAIT_FOR_ERASE\fP, \fBLCDCFG_STATE_WRITE\fP, \fBLCDCFG_STATE_CHECK_CFG\fP, \fBLCDCFG_STATE_SEND_CFG\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcd_init\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_update\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_canRecved\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_eraseDoneCallback\fP (int retval)"
.br
.ti -1c
.RI "void \fBlcd_writeFlVoltToCfg\fP (float f)"
.br
.ti -1c
.RI "void \fBlcd_runCfgStateMachine\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_loadTelemetry\fP (void)"
.br
.ti -1c
.RI "int \fBlcd_queueWrite\fP (int type)"
.br
.ti -1c
.RI "int \fBlcd_startWrite\fP (void)"
.br
.ti -1c
.RI "void \fBlcd_checkPersistentUpdate\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMMSTIMEOUT   5"

.PP
Definition at line 29 of file lcd\&.h\&.
.SS "#define DSP28_DATA_TYPES"

.PP
Definition at line 14 of file lcd\&.h\&.
.SS "#define LCD_PERIOD_MS   500"

.PP
Definition at line 28 of file lcd\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBfloat32\fP"

.PP
Definition at line 23 of file lcd\&.h\&.
.SS "typedef long double \fBfloat64\fP"

.PP
Definition at line 24 of file lcd\&.h\&.
.SS "typedef int \fBint16\fP"

.PP
Definition at line 16 of file lcd\&.h\&.
.SS "typedef long \fBint32\fP"

.PP
Definition at line 17 of file lcd\&.h\&.
.SS "typedef long long \fBint64\fP"

.PP
Definition at line 18 of file lcd\&.h\&.
.SS "typedef char \fBint8\fP"

.PP
Definition at line 15 of file lcd\&.h\&.
.SS "typedef enum \fBlcd_CfgState_\fP \fBlcd_CfgState\fP"

.SS "typedef unsigned int \fBUint16\fP"

.PP
Definition at line 20 of file lcd\&.h\&.
.SS "typedef unsigned long \fBUint32\fP"

.PP
Definition at line 21 of file lcd\&.h\&.
.SS "typedef unsigned long long \fBUint64\fP"

.PP
Definition at line 22 of file lcd\&.h\&.
.SS "typedef unsigned char \fBUint8\fP"

.PP
Definition at line 19 of file lcd\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlcd_CfgState_\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILCDCFG_STATE_CFG_IDLE \fP\fP
.TP
\fB\fILCDCFG_STATE_ERASE \fP\fP
.TP
\fB\fILCDCFG_STATE_WAIT_FOR_ERASE \fP\fP
.TP
\fB\fILCDCFG_STATE_WRITE \fP\fP
.TP
\fB\fILCDCFG_STATE_CHECK_CFG \fP\fP
.TP
\fB\fILCDCFG_STATE_SEND_CFG \fP\fP
.PP
Definition at line 31 of file lcd\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void lcd_canRecved (void)"

.PP
Definition at line 731 of file lcd\&.c\&.
.SS "void lcd_checkPersistentUpdate (void)"

.PP
Definition at line 668 of file lcd\&.c\&.
.SS "void lcd_eraseDoneCallback (int retval)"

.PP
Definition at line 736 of file lcd\&.c\&.
.SS "void lcd_init (void)"

.PP
Definition at line 91 of file lcd\&.c\&.
.SS "void lcd_loadTelemetry (void)"

.PP
Definition at line 416 of file lcd\&.c\&.
.SS "int lcd_queueWrite (int type)"

.PP
Definition at line 714 of file lcd\&.c\&.
.SS "void lcd_runCfgStateMachine (void)"

.PP
Definition at line 741 of file lcd\&.c\&.
.SS "int lcd_startWrite (void)"

.PP
Definition at line 677 of file lcd\&.c\&.
.SS "void lcd_update (void)"

.PP
Definition at line 368 of file lcd\&.c\&.
.SS "void lcd_writeFlVoltToCfg (float f)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
