.TH "LocalCfg_" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalCfg_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cfg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUInt16\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBProductCode\fP \fBproductCode\fP"
.br
.ti -1c
.RI "\fBUInt32\fP \fBserialNumber\fP"
.br
.ti -1c
.RI "\fBUInt32\fP \fBcanBaseId\fP"
.br
.ti -1c
.RI "\fBUInt32\fP \fBcanBaud\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBconfigVersion\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBoutVoltAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBoutCurrAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBpvVoltAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBpvCurrAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBrail12VoltAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBflSetSenseAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBcaseTmpAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBtmpCmpSenseAdcCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBmpptSamplePtDacCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBvinLimDacCal\fP"
.br
.ti -1c
.RI "\fBCalib\fP \fBflTrimDacCal\fP"
.br
.ti -1c
.RI "float \fBthermRinf\fP"
.br
.ti -1c
.RI "float \fBthermBeta\fP"
.br
.ti -1c
.RI "float \fBisSlave\fP"
.br
.ti -1c
.RI "float \fBoverCurrSpSw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file cfg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBUInt32\fP canBaseId"

.PP
Definition at line 101 of file cfg\&.h\&.
.SS "\fBUInt32\fP canBaud"

.PP
Definition at line 102 of file cfg\&.h\&.
.SS "\fBCalib\fP caseTmpAdcCal"

.PP
Definition at line 113 of file cfg\&.h\&.
.SS "\fBUInt16\fP checksum"

.PP
Definition at line 97 of file cfg\&.h\&.
.SS "\fBUInt16\fP configVersion"

.PP
Definition at line 105 of file cfg\&.h\&.
.SS "\fBCalib\fP flSetSenseAdcCal"

.PP
Definition at line 112 of file cfg\&.h\&.
.SS "\fBCalib\fP flTrimDacCal"

.PP
Definition at line 118 of file cfg\&.h\&.
.SS "float isSlave"

.PP
Definition at line 124 of file cfg\&.h\&.
.SS "\fBCalib\fP mpptSamplePtDacCal"

.PP
Definition at line 116 of file cfg\&.h\&.
.SS "\fBCalib\fP outCurrAdcCal"

.PP
Definition at line 108 of file cfg\&.h\&.
.SS "\fBCalib\fP outVoltAdcCal"

.PP
Definition at line 107 of file cfg\&.h\&.
.SS "float overCurrSpSw"

.PP
Definition at line 125 of file cfg\&.h\&.
.SS "\fBProductCode\fP productCode"

.PP
Definition at line 99 of file cfg\&.h\&.
.SS "\fBCalib\fP pvCurrAdcCal"

.PP
Definition at line 110 of file cfg\&.h\&.
.SS "\fBCalib\fP pvVoltAdcCal"

.PP
Definition at line 109 of file cfg\&.h\&.
.SS "\fBCalib\fP rail12VoltAdcCal"

.PP
Definition at line 111 of file cfg\&.h\&.
.SS "\fBUInt32\fP serialNumber"

.PP
Definition at line 100 of file cfg\&.h\&.
.SS "\fBUInt16\fP size"

.PP
Definition at line 98 of file cfg\&.h\&.
.SS "float thermBeta"

.PP
Definition at line 121 of file cfg\&.h\&.
.SS "float thermRinf"

.PP
Definition at line 120 of file cfg\&.h\&.
.SS "\fBCalib\fP tmpCmpSenseAdcCal"

.PP
Definition at line 114 of file cfg\&.h\&.
.SS "\fBCalib\fP vinLimDacCal"

.PP
Definition at line 117 of file cfg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
