.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/main.h" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/main.h
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br
\fC#include 'variant\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMAIN_resetAllAndStart\fP ()"
.br
.ti -1c
.RI "void \fBMAIN_resetRemoteCfg\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MAIN_resetAllAndStart ()"
dint(); //RDD comment Disable interrupts ?
.PP
eint();
.PP
Definition at line 101 of file main\&.c\&.
.SS "void MAIN_resetRemoteCfg ()"

.PP
Definition at line 169 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
