.TH "Meas_" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Meas_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <meas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBAdcCommsMeas\fP \fBoutVolt\fP"
.br
.ti -1c
.RI "\fBAdcCommsMeas\fP \fBoutCurr\fP"
.br
.ti -1c
.RI "\fBAdcCommsMeas\fP \fBpvVolt\fP"
.br
.ti -1c
.RI "\fBAdcCommsMeas\fP \fBpvCurr\fP"
.br
.ti -1c
.RI "\fBAdcMeas\fP \fBrail12Volt\fP"
.br
.ti -1c
.RI "\fBAdcMeas\fP \fBflSetSense\fP"
.br
.ti -1c
.RI "\fBAdcMeas\fP \fBcaseTmp\fP"
.br
.ti -1c
.RI "\fBAdcMeas\fP \fBtmpCmpSense\fP"
.br
.ti -1c
.RI "\fBCommsMeas\fP \fBpvPower\fP"
.br
.ti -1c
.RI "\fBCommsMeas\fP \fBpvOcVolt\fP"
.br
.ti -1c
.RI "\fBCommsMeas\fP \fBbatTempr\fP"
.br
.ti -1c
.RI "int \fBbatTemprFault\fP"
.br
.ti -1c
.RI "\fBCommsMeas\fP \fBcaseTempr\fP"
.br
.ti -1c
.RI "int \fBcaseTemprFault\fP"
.br
.ti -1c
.RI "\fBIntegralMeas\fP \fBoutCharge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file meas\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBCommsMeas\fP batTempr"

.PP
Definition at line 128 of file meas\&.h\&.
.SS "int batTemprFault"

.PP
Definition at line 129 of file meas\&.h\&.
.SS "\fBCommsMeas\fP caseTempr"

.PP
Definition at line 132 of file meas\&.h\&.
.SS "int caseTemprFault"

.PP
Definition at line 133 of file meas\&.h\&.
.SS "\fBAdcMeas\fP caseTmp"

.PP
Definition at line 119 of file meas\&.h\&.
.SS "\fBAdcMeas\fP flSetSense"

.PP
Definition at line 118 of file meas\&.h\&.
.SS "\fBIntegralMeas\fP outCharge"

.PP
Definition at line 136 of file meas\&.h\&.
.SS "\fBAdcCommsMeas\fP outCurr"

.PP
Definition at line 114 of file meas\&.h\&.
.SS "\fBAdcCommsMeas\fP outVolt"

.PP
Definition at line 113 of file meas\&.h\&.
.SS "\fBAdcCommsMeas\fP pvCurr"

.PP
Definition at line 116 of file meas\&.h\&.
.SS "\fBCommsMeas\fP pvOcVolt"

.PP
Definition at line 126 of file meas\&.h\&.
.SS "\fBCommsMeas\fP pvPower"

.PP
Definition at line 124 of file meas\&.h\&.
.SS "\fBAdcCommsMeas\fP pvVolt"

.PP
Definition at line 115 of file meas\&.h\&.
.SS "\fBAdcMeas\fP rail12Volt"

.PP
Definition at line 117 of file meas\&.h\&.
.SS "\fBAdcMeas\fP tmpCmpSense"

.PP
Definition at line 120 of file meas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
