.TH "P2p_" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P2p_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBP2pMode\fP \fBmode\fP"
.br
.ti -1c
.RI "unsigned char \fBreqChars\fP [2]"
.br
.ti -1c
.RI "unsigned long \fBcurrentAddr\fP"
.br
.ti -1c
.RI "unsigned long \fBlenRem\fP"
.br
.ti -1c
.RI "unsigned long \fBpacketCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file comms\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long currentAddr"

.PP
Definition at line 86 of file comms\&.c\&.
.SS "unsigned long lenRem"

.PP
Definition at line 87 of file comms\&.c\&.
.SS "\fBP2pMode\fP mode"

.PP
Definition at line 84 of file comms\&.c\&.
.SS "unsigned long packetCount"

.PP
Definition at line 88 of file comms\&.c\&.
.SS "unsigned char reqChars[2]"

.PP
Definition at line 85 of file comms\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
