.TH "packetIdentifier_t" 3 "Wed Nov 25 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packetIdentifier_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned char \fBtype\fP: 4"
.br
.ti -1c
.RI "   unsigned char \fBrequest\fP: 1"
.br
.ti -1c
.RI "   unsigned char \fBversion\fP: 3"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned char \fBbyte\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 282 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "unsigned char byte"

.PP
Definition at line 288 of file protocol\&.h\&.
.SS "unsigned char request"

.PP
Definition at line 285 of file protocol\&.h\&.
.SS "unsigned char type"

.PP
Definition at line 284 of file protocol\&.h\&.
.SS "unsigned char version"

.PP
Definition at line 286 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
