.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/pwm.c" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/pwm.c
.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include 'iqmath\&.h'\fP
.br
\fC#include 'pwm\&.h'\fP
.br
\fC#include 'sch\&.h'\fP
.br
\fC#include 'io\&.h'\fP
.br
\fC#include 'meas\&.h'\fP
.br
\fC#include 'ctrl\&.h'\fP
.br
\fC#include 'cfg\&.h'\fP
.br
\fC#include 'flash\&.h'\fP
.br
\fC#include 'safety\&.h'\fP
.br
\fC#include 'comms\&.h'\fP
.br
\fC#include 'variant\&.h'\fP
.br
\fC#include 'temp\&.h'\fP
.br
\fC#include 'dcdc\&.h'\fP
.br
\fC#include 'HiResTim\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPwmCalib_\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIQ_TO_PWM\fP(pwm)   (((float)(pwm)) *((float) \fBMEAS_PVVOLT_IQBASE\fP ))"
.br
.ti -1c
.RI "#define \fBPWM_MPPTSAMPLEPT_CCR\fP   TACCR2"
.br
.ti -1c
.RI "#define \fBPWM_VINLIM_CCR\fP   TACCR0"
.br
.ti -1c
.RI "#define \fBPWM_FLTRIM_CCR\fP   TACCR1"
.br
.ti -1c
.RI "#define \fBPWM_MPPTSAMPLEPT_CCTL\fP   TACCTL2"
.br
.ti -1c
.RI "#define \fBPWM_VINLIM_CCTL\fP   TACCTL0"
.br
.ti -1c
.RI "#define \fBPWM_FLTRIM_CCTL\fP   TACCTL1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBPwmCalib_\fP \fBPwmCalib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPWM_init\fP (void)"
.br
.ti -1c
.RI "void \fBPWM_setMpptSamplePt\fP (\fBIq\fP val)"
.br
.ti -1c
.RI "void \fBIO_enablePwmCtrl\fP ()"
.br
.ti -1c
.RI "void \fBIO_disablePwmCtrl\fP ()"
.br
.ti -1c
.RI "void \fBPWM_setVinLim\fP (\fBIq\fP val)"
.br
.ti -1c
.RI "void \fBPWM_setFlTrim\fP (\fBIq\fP val)"
.br
.ti -1c
.RI "void \fBPWM_isr\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPwmCalib\fP \fBmpptSamplePtCal\fP"
.br
.ti -1c
.RI "\fBPwmCalib\fP \fBvinLimCal\fP"
.br
.ti -1c
.RI "\fBPwmCalib\fP \fBflTrimCal\fP"
.br
.ti -1c
.RI "float \fBmpptSamplePtShadow\fP"
.br
.ti -1c
.RI "unsigned int \fBvinLimShadow\fP"
.br
.ti -1c
.RI "unsigned int \fBflTrimShadow\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IQ_TO_PWM(pwm)   (((float)(pwm)) *((float) \fBMEAS_PVVOLT_IQBASE\fP ))"

.PP
Definition at line 39 of file pwm\&.c\&.
.SS "#define PWM_FLTRIM_CCR   TACCR1"

.PP
Definition at line 57 of file pwm\&.c\&.
.SS "#define PWM_FLTRIM_CCTL   TACCTL1"

.PP
Definition at line 61 of file pwm\&.c\&.
.SS "#define PWM_MPPTSAMPLEPT_CCR   TACCR2"

.PP
Definition at line 55 of file pwm\&.c\&.
.SS "#define PWM_MPPTSAMPLEPT_CCTL   TACCTL2"

.PP
Definition at line 59 of file pwm\&.c\&.
.SS "#define PWM_VINLIM_CCR   TACCR0"

.PP
Definition at line 56 of file pwm\&.c\&.
.SS "#define PWM_VINLIM_CCTL   TACCTL0"

.PP
Definition at line 60 of file pwm\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBPwmCalib_\fP \fBPwmCalib\fP"

.SH "Function Documentation"
.PP 
.SS "void IO_disablePwmCtrl (void)"
RDD statusFlags\&.CONTROL_STOP=1;
.PP
Definition at line 107 of file pwm\&.c\&.
.SS "void IO_enablePwmCtrl (void)"
RDD statusFlags\&.CONTROL_START=1;
.PP
Definition at line 97 of file pwm\&.c\&.
.SS "void PWM_init (void)"

.PP
Definition at line 63 of file pwm\&.c\&.
.SS "void PWM_isr (void)"
Regulator(mpptSamplePtShadow); //RDD
.PP
Definition at line 134 of file pwm\&.c\&.
.SS "void PWM_setFlTrim (\fBIq\fP val)"

.PP
Definition at line 124 of file pwm\&.c\&.
.SS "void PWM_setMpptSamplePt (\fBIq\fP val)"

.PP
Definition at line 89 of file pwm\&.c\&.
.SS "void PWM_setVinLim (\fBIq\fP val)"

.PP
Definition at line 116 of file pwm\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBPwmCalib\fP flTrimCal"

.PP
Definition at line 49 of file pwm\&.c\&.
.SS "unsigned int flTrimShadow"

.PP
Definition at line 53 of file pwm\&.c\&.
.SS "\fBPwmCalib\fP mpptSamplePtCal"

.PP
Definition at line 47 of file pwm\&.c\&.
.SS "float mpptSamplePtShadow"

.PP
Definition at line 51 of file pwm\&.c\&.
.SS "\fBPwmCalib\fP vinLimCal"

.PP
Definition at line 48 of file pwm\&.c\&.
.SS "unsigned int vinLimShadow"

.PP
Definition at line 52 of file pwm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
