.TH "ReadonlyCfg_" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadonlyCfg_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUInt16\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBhardwareVersion\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBfirmwareVersion\fP"
.br
.ti -1c
.RI "\fBUInt32\fP \fBbuildNumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file cfg\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBUInt32\fP buildNumber"

.PP
Definition at line 101 of file cfg\&.c\&.
.SS "\fBUInt16\fP checksum"

.PP
Definition at line 97 of file cfg\&.c\&.
.SS "\fBUInt16\fP firmwareVersion"

.PP
Definition at line 100 of file cfg\&.c\&.
.SS "\fBUInt16\fP hardwareVersion"

.PP
Definition at line 99 of file cfg\&.c\&.
.SS "\fBUInt16\fP size"

.PP
Definition at line 98 of file cfg\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
