.TH "RemoteCfg_" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemoteCfg_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cfg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUInt16\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBFlagCfgSimple\fP \fBsystemInitFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgTrig\fP \fBlowOutVoltWarnFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgTrig\fP \fBlowOutVoltFaultFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgHold\fP \fBlowOutVoltGensetFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgTrig\fP \fBhighOutVoltFaultFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgTrig\fP \fBhighOutCurrFaultFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgTrig\fP \fBhighDisCurrFaultFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgTrig\fP \fBhighTempFaultFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgSimple\fP \fBinBreakerOpenFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgSimple\fP \fBoutBreakerOpenFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgSimple\fP \fBtempSenseFaultFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgSimple\fP \fBsdFlags\fP [\fBSAFETY_NUM_SD_REASONS\fP \- 2]"
.br
.ti -1c
.RI "\fBFlagCfgSimple\fP \fBlogFullFlag\fP"
.br
.ti -1c
.RI "\fBFlagCfgSched\fP \fBpanelMissingFlag\fP"
.br
.ti -1c
.RI "\fBTELEM_SamplePeriod\fP \fBtelemSamplePeriod\fP"
.br
.ti -1c
.RI "\fBUInt16\fP \fBtelemEnableBitfield\fP"
.br
.ti -1c
.RI "float \fBpvOcVolt\fP"
.br
.ti -1c
.RI "float \fBpvMpVolt\fP"
.br
.ti -1c
.RI "float \fBfloatVolt\fP"
.br
.ti -1c
.RI "float \fBbulkVolt\fP"
.br
.ti -1c
.RI "float \fBbulkTime\fP"
.br
.ti -1c
.RI "float \fBbulkResetVolt\fP"
.br
.ti -1c
.RI "float \fBtmpCmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file cfg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float bulkResetVolt"

.PP
Definition at line 157 of file cfg\&.h\&.
.SS "float bulkTime"

.PP
Definition at line 156 of file cfg\&.h\&.
.SS "float bulkVolt"

.PP
Definition at line 155 of file cfg\&.h\&.
.SS "\fBUInt16\fP checksum"

.PP
Definition at line 131 of file cfg\&.h\&.
.SS "float floatVolt"

.PP
Definition at line 154 of file cfg\&.h\&.
.SS "\fBFlagCfgTrig\fP highDisCurrFaultFlag"

.PP
Definition at line 140 of file cfg\&.h\&.
.SS "\fBFlagCfgTrig\fP highOutCurrFaultFlag"

.PP
Definition at line 139 of file cfg\&.h\&.
.SS "\fBFlagCfgTrig\fP highOutVoltFaultFlag"

.PP
Definition at line 138 of file cfg\&.h\&.
.SS "\fBFlagCfgTrig\fP highTempFaultFlag"

.PP
Definition at line 141 of file cfg\&.h\&.
.SS "\fBFlagCfgSimple\fP inBreakerOpenFlag"

.PP
Definition at line 142 of file cfg\&.h\&.
.SS "\fBFlagCfgSimple\fP logFullFlag"

.PP
Definition at line 146 of file cfg\&.h\&.
.SS "\fBFlagCfgTrig\fP lowOutVoltFaultFlag"

.PP
Definition at line 136 of file cfg\&.h\&.
.SS "\fBFlagCfgHold\fP lowOutVoltGensetFlag"

.PP
Definition at line 137 of file cfg\&.h\&.
.SS "\fBFlagCfgTrig\fP lowOutVoltWarnFlag"

.PP
Definition at line 135 of file cfg\&.h\&.
.SS "\fBFlagCfgSimple\fP outBreakerOpenFlag"

.PP
Definition at line 143 of file cfg\&.h\&.
.SS "\fBFlagCfgSched\fP panelMissingFlag"

.PP
Definition at line 147 of file cfg\&.h\&.
.SS "float pvMpVolt"

.PP
Definition at line 153 of file cfg\&.h\&.
.SS "float pvOcVolt"

.PP
Definition at line 152 of file cfg\&.h\&.
.SS "\fBFlagCfgSimple\fP sdFlags[\fBSAFETY_NUM_SD_REASONS\fP \- 2]"

.PP
Definition at line 145 of file cfg\&.h\&.
.SS "\fBUInt16\fP size"

.PP
Definition at line 132 of file cfg\&.h\&.
.SS "\fBFlagCfgSimple\fP systemInitFlag"

.PP
Definition at line 134 of file cfg\&.h\&.
.SS "\fBUInt16\fP telemEnableBitfield"

.PP
Definition at line 150 of file cfg\&.h\&.
.SS "\fBTELEM_SamplePeriod\fP telemSamplePeriod"

.PP
Definition at line 149 of file cfg\&.h\&.
.SS "\fBFlagCfgSimple\fP tempSenseFaultFlag"

.PP
Definition at line 144 of file cfg\&.h\&.
.SS "float tmpCmp"

.PP
Definition at line 158 of file cfg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
