.TH "Safety_" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Safety_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBsdBits\fP"
.br
.ti -1c
.RI "unsigned int \fBpvCurrNegTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBdelayedRetryTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBoutVoltOCDelayTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBoutVoltRstDelayTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBoutCurrDelayTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBPVVoltLowSrtupDelayTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBPVVoltLowRstDelayTickCnt\fP"
.br
.ti -1c
.RI "unsigned long \fBlowPVShutdownInt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file safety\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long delayedRetryTickCnt"

.PP
Definition at line 58 of file safety\&.c\&.
.SS "unsigned long lowPVShutdownInt"

.PP
Definition at line 64 of file safety\&.c\&.
.SS "unsigned long outCurrDelayTickCnt"

.PP
Definition at line 61 of file safety\&.c\&.
.SS "unsigned long outVoltOCDelayTickCnt"

.PP
Definition at line 59 of file safety\&.c\&.
.SS "unsigned long outVoltRstDelayTickCnt"

.PP
Definition at line 60 of file safety\&.c\&.
.SS "unsigned int pvCurrNegTickCnt"

.PP
Definition at line 57 of file safety\&.c\&.
.SS "unsigned long PVVoltLowRstDelayTickCnt"

.PP
Definition at line 63 of file safety\&.c\&.
.SS "unsigned long PVVoltLowSrtupDelayTickCnt"

.PP
Definition at line 62 of file safety\&.c\&.
.SS "unsigned int sdBits"

.PP
Definition at line 56 of file safety\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
