.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/safety.c" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/safety.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mainMSP\&.h'\fP
.br
\fC#include 'safety\&.h'\fP
.br
\fC#include 'meas\&.h'\fP
.br
\fC#include 'io\&.h'\fP
.br
\fC#include 'cfg\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSafety_\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPVCURR_NEG_MIN_TICKS\fP   1"
.br
.RI "#include <msp430x24x\&.h> "
.ti -1c
.RI "#define \fBSAFETY_DELAYED_RETRY_TICKS\fP   1"
.br
.ti -1c
.RI "#define \fBOUTVOLT_OC_DELAY_TICKS\fP   1"
.br
.ti -1c
.RI "#define \fBOUTCURR_DELAY_TICKS\fP   1"
.br
.ti -1c
.RI "#define \fBOUTVOLT_RST_DELAY_TICKS\fP   1"
.br
.ti -1c
.RI "#define \fBPVVOLTLOW_SRTUP_DELAY_TICKS\fP   1"
.br
.ti -1c
.RI "#define \fBPVVOLTLOW_RST_DELAY_TICKS\fP   1"
.br
.ti -1c
.RI "#define \fBSAFETY_IO_VOLTAGE_THRESHOLD\fP   2"
.br
.ti -1c
.RI "#define \fBSAFETY_OUTCURRCRIT_LIMIT\fP   90"
.br
.ti -1c
.RI "#define \fBSAFETY_PVVOLT_LIMIT_HV\fP   290\&.0"
.br
.ti -1c
.RI "#define \fBSAFETY_OUTCURR_LIMIT_HV\fP   65"
.br
.ti -1c
.RI "#define \fBSAFETY_OUTVOLT_OVER_LIMIT_HV\fP   3"
.br
.ti -1c
.RI "#define \fBSAFETY_PULSE_CURRENT_LIMIT_HV\fP   \fBIQ_cnst\fP(65\&.0 / \fBMEAS_PVCURR_BASE\fP)"
.br
.ti -1c
.RI "#define \fBSAFETY_PULSE_CURRENT_LIMIT_MV\fP   \fBIQ_cnst\fP(85\&.0 / \fBMEAS_PVCURR_BASE\fP)"
.br
.ti -1c
.RI "#define \fBSAFETY_PVVOLT_LIMIT_MV\fP   180\&.0"
.br
.ti -1c
.RI "#define \fBSAFETY_OUTCURR_LIMIT_MV\fP   85"
.br
.ti -1c
.RI "#define \fBSAFETY_OUTVOLT_OVER_LIMIT_MV\fP   3"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBSafety_\fP \fBSafety\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSAFETY_init\fP ()"
.br
.ti -1c
.RI "void \fBSAFETY_setLimitsMV\fP ()"
.br
.ti -1c
.RI "void \fBSAFETY_setLimitsHV\fP ()"
.br
.ti -1c
.RI "void \fBSAFETY_tick\fP ()"
.br
.ti -1c
.RI "void \fBSAFETY_monitor\fP ()"
.br
.ti -1c
.RI "void \fBSAFETY_fanShutdown\fP ()"
.br
.ti -1c
.RI "unsigned char \fBSAFETY_getStatus\fP ()"
.br
.ti -1c
.RI "int \fBSAFETY_isShutdown\fP (int reason)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBIq\fP \fBSAFETY_PVVoltLimit\fP = 0"
.br
.ti -1c
.RI "\fBIq\fP \fBSAFETY_OutCurrLimit\fP = 0"
.br
.ti -1c
.RI "\fBIq\fP \fBSAFETY_OutCurrCrit\fP = 0"
.br
.ti -1c
.RI "\fBIq\fP \fBSAFETY_PulseCurrLimit\fP = 0"
.br
.ti -1c
.RI "\fBIq\fP \fBSAFETY_OutVoltLimit\fP = 0"
.br
.ti -1c
.RI "\fBIq\fP \fBSAFETY_OutVoltRstHigh\fP = 0"
.br
.ti -1c
.RI "\fBIq\fP \fBSAFETY_OutVoltRstLow\fP = 0"
.br
.ti -1c
.RI "\fBSafety\fP \fBsafety\fP"
.br
.ti -1c
.RI "unsigned char \fBsamplePending\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OUTCURR_DELAY_TICKS   1"

.PP
Definition at line 26 of file safety\&.c\&.
.SS "#define OUTVOLT_OC_DELAY_TICKS   1"

.PP
Definition at line 25 of file safety\&.c\&.
.SS "#define OUTVOLT_RST_DELAY_TICKS   1"

.PP
Definition at line 27 of file safety\&.c\&.
.SS "#define PVCURR_NEG_MIN_TICKS   1"

.PP
#include <msp430x24x\&.h> #include 'pwm\&.h' #include 'flag\&.h' include 'comms\&.h' include <signal\&.h> 
.PP
Definition at line 23 of file safety\&.c\&.
.SS "#define PVVOLTLOW_RST_DELAY_TICKS   1"

.PP
Definition at line 29 of file safety\&.c\&.
.SS "#define PVVOLTLOW_SRTUP_DELAY_TICKS   1"

.PP
Definition at line 28 of file safety\&.c\&.
.SS "#define SAFETY_DELAYED_RETRY_TICKS   1"

.PP
Definition at line 24 of file safety\&.c\&.
.SS "#define SAFETY_IO_VOLTAGE_THRESHOLD   2"

.PP
Definition at line 31 of file safety\&.c\&.
.SS "#define SAFETY_OUTCURR_LIMIT_HV   65"

.PP
Definition at line 35 of file safety\&.c\&.
.SS "#define SAFETY_OUTCURR_LIMIT_MV   85"

.PP
Definition at line 41 of file safety\&.c\&.
.SS "#define SAFETY_OUTCURRCRIT_LIMIT   90"

.PP
Definition at line 32 of file safety\&.c\&.
.SS "#define SAFETY_OUTVOLT_OVER_LIMIT_HV   3"

.PP
Definition at line 36 of file safety\&.c\&.
.SS "#define SAFETY_OUTVOLT_OVER_LIMIT_MV   3"

.PP
Definition at line 42 of file safety\&.c\&.
.SS "#define SAFETY_PULSE_CURRENT_LIMIT_HV   \fBIQ_cnst\fP(65\&.0 / \fBMEAS_PVCURR_BASE\fP)"

.PP
Definition at line 37 of file safety\&.c\&.
.SS "#define SAFETY_PULSE_CURRENT_LIMIT_MV   \fBIQ_cnst\fP(85\&.0 / \fBMEAS_PVCURR_BASE\fP)"

.PP
Definition at line 39 of file safety\&.c\&.
.SS "#define SAFETY_PVVOLT_LIMIT_HV   290\&.0"

.PP
Definition at line 34 of file safety\&.c\&.
.SS "#define SAFETY_PVVOLT_LIMIT_MV   180\&.0"

.PP
Definition at line 40 of file safety\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSafety_\fP \fBSafety\fP"

.SH "Function Documentation"
.PP 
.SS "void SAFETY_fanShutdown (void)"

.PP
Definition at line 285 of file safety\&.c\&.
.SS "unsigned char SAFETY_getStatus (void)"

.PP
Definition at line 290 of file safety\&.c\&.
.SS "void SAFETY_init (void)"

.PP
Definition at line 71 of file safety\&.c\&.
.SS "int SAFETY_isShutdown (int reason)"

.PP
Definition at line 302 of file safety\&.c\&.
.SS "void SAFETY_monitor (void)"

.PP
Definition at line 195 of file safety\&.c\&.
.SS "void SAFETY_setLimitsHV (void)"

.PP
Definition at line 95 of file safety\&.c\&.
.SS "void SAFETY_setLimitsMV (void)"

.PP
Definition at line 84 of file safety\&.c\&.
.SS "void SAFETY_tick (void)"
RDDtemp \fBIO_disablePwmCtrl()\fP;
.PP
Definition at line 106 of file safety\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBSafety\fP safety"

.PP
Definition at line 67 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_OutCurrCrit = 0"

.PP
Definition at line 47 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_OutCurrLimit = 0"

.PP
Definition at line 46 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_OutVoltLimit = 0"

.PP
Definition at line 49 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_OutVoltRstHigh = 0"

.PP
Definition at line 50 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_OutVoltRstLow = 0"

.PP
Definition at line 51 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_PulseCurrLimit = 0"

.PP
Definition at line 48 of file safety\&.c\&.
.SS "\fBIq\fP SAFETY_PVVoltLimit = 0"

.PP
Definition at line 45 of file safety\&.c\&.
.SS "unsigned char samplePending = 0"

.PP
Definition at line 69 of file safety\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
