.TH "setTime_t" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setTime_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint64_t \fBtime\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned char \fBbytes\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 220 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "unsigned char bytes[1]"

.PP
Definition at line 224 of file protocol\&.h\&.
.SS "uint64_t time"

.PP
Definition at line 222 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
