.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/status.h" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/status.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBStatus\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSTATUS_init\fP ()"
.br
.ti -1c
.RI "void \fBSTATUS_update\fP ()"
.br
.ti -1c
.RI "unsigned long long \fBSTATUS_getStatus\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBStatus\fP"

.PP
Definition at line 15 of file status\&.h\&.
.SH "Function Documentation"
.PP 
.SS "unsigned long long STATUS_getStatus ()"

.PP
Definition at line 68 of file status\&.c\&.
.SS "void STATUS_init ()"

.PP
Definition at line 50 of file status\&.c\&.
.SS "void STATUS_update ()"

.PP
Definition at line 55 of file status\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
