.TH "StatHelper_" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatHelper_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIqLong\fP \fBtempSum\fP"
.br
.ti -1c
.RI "long \fBnumTempUpdates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file stats\&.c\&.
.SH "Field Documentation"
.PP 
.SS "long numTempUpdates"

.PP
Definition at line 34 of file stats\&.c\&.
.SS "\fBIqLong\fP tempSum"

.PP
Definition at line 33 of file stats\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
