.TH "Stats_" 3 "Thu Nov 26 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stats_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBStatistics\fP \fBstatistics\fP"
.br
.ti -1c
.RI "\fBStatHelper\fP \fBstatHelpers\fP [\fBStatId_NUM\fP]"
.br
.ti -1c
.RI "unsigned long \fBcurrentAddr\fP"
.br
.ti -1c
.RI "int \fBisReadyToUpdate\fP"
.br
.ti -1c
.RI "int \fBisReadyToWrite\fP"
.br
.ti -1c
.RI "int \fBisErasing\fP"
.br
.ti -1c
.RI "int \fBisWritePending\fP"
.br
.ti -1c
.RI "int \fBisErasePending\fP"
.br
.ti -1c
.RI "int \fBisFirst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file stats\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long currentAddr"

.PP
Definition at line 50 of file stats\&.c\&.
.SS "int isErasePending"

.PP
Definition at line 55 of file stats\&.c\&.
.SS "int isErasing"

.PP
Definition at line 53 of file stats\&.c\&.
.SS "int isFirst"

.PP
Definition at line 56 of file stats\&.c\&.
.SS "int isReadyToUpdate"

.PP
Definition at line 51 of file stats\&.c\&.
.SS "int isReadyToWrite"

.PP
Definition at line 52 of file stats\&.c\&.
.SS "int isWritePending"

.PP
Definition at line 54 of file stats\&.c\&.
.SS "\fBStatHelper\fP statHelpers[\fBStatId_NUM\fP]"

.PP
Definition at line 49 of file stats\&.c\&.
.SS "\fBStatistics\fP statistics"

.PP
Definition at line 48 of file stats\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
