.TH "Statistics" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistics
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTime\fP \fBlastWriteTime\fP"
.br
.ti -1c
.RI "long \fBnumUpdates\fP"
.br
.ti -1c
.RI "\fBStatistic\fP \fBstatistics\fP [\fBStatId_NUM\fP]"
.br
.ti -1c
.RI "\fBIqLong\fP \fBoutCharge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file stats\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBTime\fP lastWriteTime"

.PP
Definition at line 40 of file stats\&.c\&.
.SS "long numUpdates"

.PP
Definition at line 41 of file stats\&.c\&.
.SS "\fBIqLong\fP outCharge"

.PP
Definition at line 43 of file stats\&.c\&.
.SS "\fBStatistic\fP statistics[\fBStatId_NUM\fP]"

.PP
Definition at line 42 of file stats\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
