.TH "sysInfo_t" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sysInfo_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char \fBhwVersion\fP [8]"
.br
.ti -1c
.RI "   char \fBfwVersion\fP [8]"
.br
.ti -1c
.RI "   char \fBmodelType\fP [4]"
.br
.ti -1c
.RI "   char \fBproductID\fP [8]"
.br
.ti -1c
.RI "   char \fBserialNumber\fP [8]"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned char \fBbytes\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 194 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "unsigned char bytes[1]"

.PP
Definition at line 202 of file protocol\&.h\&.
.SS "char fwVersion[8]"

.PP
Definition at line 197 of file protocol\&.h\&.
.SS "char hwVersion[8]"

.PP
Definition at line 196 of file protocol\&.h\&.
.SS "char modelType[4]"

.PP
Definition at line 198 of file protocol\&.h\&.
.SS "char productID[8]"

.PP
Definition at line 199 of file protocol\&.h\&.
.SS "char serialNumber[8]"

.PP
Definition at line 200 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
