.TH "TaskDef_" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskDef_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBperiod_ms\fP"
.br
.ti -1c
.RI "int \fBcounter_ms\fP"
.br
.ti -1c
.RI "void(* \fBpFunc\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file sch\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int counter_ms"

.PP
Definition at line 32 of file sch\&.c\&.
.SS "int period_ms"

.PP
Definition at line 31 of file sch\&.c\&.
.SS "void(* pFunc) (void)"

.PP
Definition at line 33 of file sch\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
