.TH "Telem_" 3 "Fri Nov 27 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Telem_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBisReady\fP"
.br
.ti -1c
.RI "int \fBisFull\fP"
.br
.ti -1c
.RI "unsigned int \fBcallCount\fP"
.br
.ti -1c
.RI "unsigned int \fBqueuedWrites\fP"
.br
.ti -1c
.RI "unsigned int \fBwritesPerSector\fP"
.br
.ti -1c
.RI "unsigned int \fBwritesLeftThisSector\fP"
.br
.ti -1c
.RI "unsigned long \fBstartAddr\fP"
.br
.ti -1c
.RI "unsigned long \fBendAddr\fP"
.br
.ti -1c
.RI "unsigned long \fBcurrentAddr\fP"
.br
.ti -1c
.RI "unsigned int \fBcurrentTelemBlock\fP"
.br
.ti -1c
.RI "unsigned long \fBmemLen\fP"
.br
.ti -1c
.RI "\fBTelemHeader\fP \fBheader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file telem\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int callCount"

.PP
Definition at line 71 of file telem\&.c\&.
.SS "unsigned long currentAddr"

.PP
Definition at line 77 of file telem\&.c\&.
.SS "unsigned int currentTelemBlock"

.PP
Definition at line 78 of file telem\&.c\&.
.SS "unsigned long endAddr"

.PP
Definition at line 76 of file telem\&.c\&.
.SS "\fBTelemHeader\fP header"

.PP
Definition at line 80 of file telem\&.c\&.
.SS "int isFull"

.PP
Definition at line 70 of file telem\&.c\&.
.SS "int isReady"

.PP
Definition at line 69 of file telem\&.c\&.
.SS "unsigned long memLen"

.PP
Definition at line 79 of file telem\&.c\&.
.SS "unsigned int queuedWrites"

.PP
Definition at line 72 of file telem\&.c\&.
.SS "unsigned long startAddr"

.PP
Definition at line 75 of file telem\&.c\&.
.SS "unsigned int writesLeftThisSector"

.PP
Definition at line 74 of file telem\&.c\&.
.SS "unsigned int writesPerSector"

.PP
Definition at line 73 of file telem\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
