.TH "telemetry_t" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
telemetry_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char \fBproductID\fP [8]"
.br
.ti -1c
.RI "   char \fBserialNumber\fP [8]"
.br
.ti -1c
.RI "   float \fBpvVoltage\fP"
.br
.ti -1c
.RI "   float \fBpvCurrent\fP"
.br
.ti -1c
.RI "   float \fBoutputVoltage\fP"
.br
.ti -1c
.RI "   float \fBoutputCurrent\fP"
.br
.ti -1c
.RI "   float \fBocVoltage\fP"
.br
.ti -1c
.RI "   float \fBoutputCharge\fP"
.br
.ti -1c
.RI "   float \fBpvPower\fP"
.br
.ti -1c
.RI "   float \fBbatteryTemp\fP"
.br
.ti -1c
.RI "   \fBeventFlags_t\fP \fBeventFlags\fP"
.br
.ti -1c
.RI "   \fBstatus_t\fP \fBstatus\fP"
.br
.ti -1c
.RI "   uint64_t \fBtime\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned char \fBbytes\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "float batteryTemp"

.PP
Definition at line 80 of file protocol\&.h\&.
.SS "unsigned char bytes[1]"

.PP
Definition at line 85 of file protocol\&.h\&.
.SS "\fBeventFlags_t\fP eventFlags"

.PP
Definition at line 81 of file protocol\&.h\&.
.SS "float ocVoltage"

.PP
Definition at line 77 of file protocol\&.h\&.
.SS "float outputCharge"

.PP
Definition at line 78 of file protocol\&.h\&.
.SS "float outputCurrent"

.PP
Definition at line 76 of file protocol\&.h\&.
.SS "float outputVoltage"

.PP
Definition at line 75 of file protocol\&.h\&.
.SS "char productID[8]"

.PP
Definition at line 71 of file protocol\&.h\&.
.SS "float pvCurrent"

.PP
Definition at line 74 of file protocol\&.h\&.
.SS "float pvPower"

.PP
Definition at line 79 of file protocol\&.h\&.
.SS "float pvVoltage"

.PP
Definition at line 73 of file protocol\&.h\&.
.SS "char serialNumber[8]"

.PP
Definition at line 72 of file protocol\&.h\&.
.SS "\fBstatus_t\fP status"

.PP
Definition at line 82 of file protocol\&.h\&.
.SS "uint64_t time"

.PP
Definition at line 83 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
