.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/temp.h" 3 "Fri Nov 27 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/temp.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTEMP_init\fP (void)"
.br
.ti -1c
.RI "void \fBTEMP_tick\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBTEMP_getValue\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int TEMP_getValue (void)"

.PP
Definition at line 75 of file temp\&.c\&.
.SS "void TEMP_init (void)"

.PP
Definition at line 23 of file temp\&.c\&.
.SS "void TEMP_tick (void)"

.PP
Definition at line 37 of file temp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
