.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/temp.h" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/temp.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTEMP_init\fP (void)"
.br
.RI "temperature = (273\&.15f + 25) * 64; "
.ti -1c
.RI "void \fBTEMP_tick\fP (void)"
.br
.RI "Just returns the state of the input\&. "
.ti -1c
.RI "unsigned int \fBTEMP_getValue\fP (void)"
.br
.RI "Just returns the state of the temperature in Kelvin * 64\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
