.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/temp.c" 3 "Fri Nov 27 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/temp.c
.SH SYNOPSIS
.br
.PP
\fC#include 'temp\&.h'\fP
.br
\fC#include 'time\&.h'\fP
.br
\fC#include 'io\&.h'\fP
.br
\fC#include 'pwm\&.h'\fP
.br
\fC#include 'limits\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTEMP_init\fP ()"
.br
.ti -1c
.RI "void \fBTEMP_tick\fP ()"
.br
.ti -1c
.RI "unsigned int \fBTEMP_getValue\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int TEMP_getValue (void)"

.PP
Definition at line 75 of file temp\&.c\&.
.SS "void TEMP_init (void)"

.PP
Definition at line 23 of file temp\&.c\&.
.SS "void TEMP_tick (void)"

.PP
Definition at line 37 of file temp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
