.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/time.h" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/time.h
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned long long \fBTime\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBTimeShort\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIME_init\fP (void)"
.br
.ti -1c
.RI "void \fBTIME_tick\fP (void)"
.br
.ti -1c
.RI "void \fBtime_updateTimeFromLCD\fP (void)"
.br
.ti -1c
.RI "void \fBTIME_recFromBc\fP (\fBTime\fP tm)"
.br
.ti -1c
.RI "void \fBTIME_set\fP (\fBTime\fP tm)"
.br
.ti -1c
.RI "int \fBTIME_isSet\fP (void)"
.br
.ti -1c
.RI "\fBTime\fP \fBTIME_get\fP (void)"
.br
.ti -1c
.RI "\fBTime\fP \fBTIME_getToday\fP (void)"
.br
.ti -1c
.RI "\fBTime\fP \fBTIME_getSinceToday\fP (void)"
.br
.ti -1c
.RI "int \fBTIME_isToday\fP (\fBTime\fP tm)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned long long \fBTime\fP"

.PP
Definition at line 18 of file time\&.h\&.
.SS "typedef unsigned long \fBTimeShort\fP"

.PP
Definition at line 21 of file time\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBTime\fP TIME_get (void)"

.PP
Definition at line 106 of file time\&.c\&.
.SS "\fBTime\fP TIME_getSinceToday (void)"

.PP
Definition at line 116 of file time\&.c\&.
.SS "\fBTime\fP TIME_getToday (void)"

.PP
Definition at line 111 of file time\&.c\&.
.SS "void TIME_init (void)"
RDD OLD hardware PWM_PERIOD_US;
.PP
Definition at line 39 of file time\&.c\&.
.SS "int TIME_isSet (void)"

.PP
Definition at line 101 of file time\&.c\&.
.SS "int TIME_isToday (\fBTime\fP tm)"

.PP
Definition at line 121 of file time\&.c\&.
.SS "void TIME_recFromBc (\fBTime\fP tm)"

.PP
Definition at line 72 of file time\&.c\&.
.SS "void TIME_set (\fBTime\fP tm)"

.PP
Definition at line 88 of file time\&.c\&.
.SS "void TIME_tick (void)"

.PP
Definition at line 48 of file time\&.c\&.
.SS "void time_updateTimeFromLCD (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
