.TH "D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/time.c" 3 "Sat Nov 28 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/time.c
.SH SYNOPSIS
.br
.PP
\fC#include 'time\&.h'\fP
.br
\fC#include 'telem\&.h'\fP
.br
\fC#include 'stats\&.h'\fP
.br
\fC#include 'flag\&.h'\fP
.br
\fC#include 'pwm\&.h'\fP
.br
\fC#include 'sch\&.h'\fP
.br
\fC#include 'meas\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMS_PER_DAY\fP   ( 24ull * 3600ull * 1000ull )"
.br
.ti -1c
.RI "#define \fBPWM_PERIOD_MS_MAX\fP   ( \fBPWM_PERIOD_US\fP + (\fBPWM_PERIOD_US\fP>>2) )"
.br
.ti -1c
.RI "#define \fBPWM_PERIOD_MS_MIN\fP   ( \fBPWM_PERIOD_US\fP \- (\fBPWM_PERIOD_US\fP>>2) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIME_init\fP ()"
.br
.ti -1c
.RI "void \fBTIME_tick\fP ()"
.br
.ti -1c
.RI "void \fBTIME_recFromBc\fP (\fBTime\fP tm)"
.br
.ti -1c
.RI "void \fBTIME_set\fP (\fBTime\fP tm)"
.br
.ti -1c
.RI "int \fBTIME_isSet\fP ()"
.br
.ti -1c
.RI "\fBTime\fP \fBTIME_get\fP ()"
.br
.ti -1c
.RI "\fBTime\fP \fBTIME_getToday\fP ()"
.br
.ti -1c
.RI "\fBTime\fP \fBTIME_getSinceToday\fP ()"
.br
.ti -1c
.RI "int \fBTIME_isToday\fP (\fBTime\fP tm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile \fBTime\fP \fBcurrentTime_ms\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBmicroSecs\fP"
.br
.ti -1c
.RI "int \fBpwmPeriodUs\fP"
.br
.ti -1c
.RI "\fBTime\fP \fBtoday_ms\fP"
.br
.ti -1c
.RI "int \fBtimeIsValid\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MS_PER_DAY   ( 24ull * 3600ull * 1000ull )"

.PP
Definition at line 21 of file time\&.c\&.
.SS "#define PWM_PERIOD_MS_MAX   ( \fBPWM_PERIOD_US\fP + (\fBPWM_PERIOD_US\fP>>2) )"

.PP
Definition at line 29 of file time\&.c\&.
.SS "#define PWM_PERIOD_MS_MIN   ( \fBPWM_PERIOD_US\fP \- (\fBPWM_PERIOD_US\fP>>2) )"

.PP
Definition at line 30 of file time\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBTime\fP TIME_get (void)"

.PP
Definition at line 106 of file time\&.c\&.
.SS "\fBTime\fP TIME_getSinceToday (void)"

.PP
Definition at line 116 of file time\&.c\&.
.SS "\fBTime\fP TIME_getToday (void)"

.PP
Definition at line 111 of file time\&.c\&.
.SS "void TIME_init (void)"
RDD OLD hardware PWM_PERIOD_US;
.PP
Definition at line 39 of file time\&.c\&.
.SS "int TIME_isSet (void)"

.PP
Definition at line 101 of file time\&.c\&.
.SS "int TIME_isToday (\fBTime\fP tm)"

.PP
Definition at line 121 of file time\&.c\&.
.SS "void TIME_recFromBc (\fBTime\fP tm)"

.PP
Definition at line 72 of file time\&.c\&.
.SS "void TIME_set (\fBTime\fP tm)"

.PP
Definition at line 88 of file time\&.c\&.
.SS "void TIME_tick (void)"

.PP
Definition at line 48 of file time\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBTime\fP currentTime_ms"

.PP
Definition at line 33 of file time\&.c\&.
.SS "volatile unsigned int microSecs"

.PP
Definition at line 34 of file time\&.c\&.
.SS "int pwmPeriodUs"

.PP
Definition at line 35 of file time\&.c\&.
.SS "int timeIsValid"

.PP
Definition at line 37 of file time\&.c\&.
.SS "\fBTime\fP today_ms"

.PP
Definition at line 36 of file time\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
