.TH "D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/usci.h" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/user/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/usci.h
.SH SYNOPSIS
.br
.PP
\fC#include 'protocol\&.h'\fP
.br
\fC#include 'debug\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPACKET_LENGTH\fP   254"
.br
.ti -1c
.RI "#define \fBPACKET_HEARTBEAT\fP   0x01"
.br
.ti -1c
.RI "#define \fBPACKET_NEW_FLOAT\fP   0x02"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuart_tx\fP (void)"
.br
.RI "this must be plased to HardWareLevel Group "
.ti -1c
.RI "void \fBuart_init\fP (void)"
.br
.RI "
.IP "\(bu" 2

.PP
"
.ti -1c
.RI "int \fBuart_send\fP (int type)"
.br
.ti -1c
.RI "void \fBuart_receive\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtelemetry_t\fP \fBtelemetry_R\fP"
.br
.ti -1c
.RI "\fBfactoryConfig_t\fP \fBfactoryConfig_R\fP"
.br
.ti -1c
.RI "\fBuserConfig_t\fP \fBuserConfig_R\fP"
.br
.ti -1c
.RI "\fBeventConfig_t\fP \fBeventConfig_R\fP"
.br
.ti -1c
.RI "\fBsysInfo_t\fP \fBsysInfo_R\fP"
.br
.ti -1c
.RI "\fBcommand_t\fP \fBcommand_R\fP"
.br
.ti -1c
.RI "\fBmiscState_t\fP \fBmiscState_R\fP"
.br
.ti -1c
.RI "\fBfactoryConfig_t\fP \fBfactoryConfig_W\fP"
.br
.ti -1c
.RI "\fBuserConfig_t\fP \fBuserConfig_W\fP"
.br
.ti -1c
.RI "\fBeventConfig_t\fP \fBeventConfig_W\fP"
.br
.ti -1c
.RI "\fBsetTime_t\fP \fBsetTime_W\fP"
.br
.ti -1c
.RI "\fBmiscState_t\fP \fBmiscState_W\fP"
.br
.ti -1c
.RI "\fBpersistentStorage_t\fP \fBpersistentStorage\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PACKET_HEARTBEAT   0x01"

.PP
Definition at line 18 of file usci\&.h\&.
.SS "#define PACKET_LENGTH   254"

.PP
Definition at line 16 of file usci\&.h\&.
.SS "#define PACKET_NEW_FLOAT   0x02"

.PP
Definition at line 19 of file usci\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void uart_init (void)"

.PP

.IP "\(bu" 2

.PP

.IP "\(bu" 2

.PP

.PP
Definition at line 111 of file usci\&.c\&.
.SS "void uart_receive (void)"
sent_startup used only here
.PP
RDDtemp \fBIO_disablePwmCtrl()\fP; remove old hardware WDTCTL = 0x00;
.PP
Definition at line 193 of file usci\&.c\&.
.SS "int uart_send (int type)"

.PP
Definition at line 370 of file usci\&.c\&.
.SS "void uart_tx (void)"

.PP
this must be plased to HardWareLevel Group remove old hardware IFG2 &= ~UCA0TXIFG;
.PP
remove old hardware IE2 |= UCA0TXIE;
.PP
remove old hardware UCA0TXBUF = tx_buffer[tx_count++];
.PP
Definition at line 138 of file usci\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBcommand_t\fP command_R\fC [extern]\fP"

.PP
Definition at line 69 of file usci\&.c\&.
.SS "\fBeventConfig_t\fP eventConfig_R\fC [extern]\fP"

.PP
Definition at line 67 of file usci\&.c\&.
.SS "\fBeventConfig_t\fP eventConfig_W\fC [extern]\fP"

.PP
Definition at line 75 of file usci\&.c\&.
.SS "\fBfactoryConfig_t\fP factoryConfig_R\fC [extern]\fP"

.PP
Definition at line 65 of file usci\&.c\&.
.SS "\fBfactoryConfig_t\fP factoryConfig_W\fC [extern]\fP"

.PP
Definition at line 73 of file usci\&.c\&.
.SS "\fBmiscState_t\fP miscState_R\fC [extern]\fP"

.PP
Definition at line 71 of file usci\&.c\&.
.SS "\fBmiscState_t\fP miscState_W\fC [extern]\fP"

.PP
Definition at line 78 of file usci\&.c\&.
.SS "\fBpersistentStorage_t\fP persistentStorage\fC [extern]\fP"

.PP
Definition at line 80 of file usci\&.c\&.
.SS "\fBsetTime_t\fP setTime_W\fC [extern]\fP"

.PP
Definition at line 77 of file usci\&.c\&.
.SS "\fBsysInfo_t\fP sysInfo_R\fC [extern]\fP"

.PP
Definition at line 68 of file usci\&.c\&.
.SS "\fBtelemetry_t\fP telemetry_R\fC [extern]\fP"

.PP
Definition at line 64 of file usci\&.c\&.
.SS "\fBuserConfig_t\fP userConfig_R\fC [extern]\fP"

.PP
Definition at line 66 of file usci\&.c\&.
.SS "\fBuserConfig_t\fP userConfig_W\fC [extern]\fP"

.PP
Definition at line 74 of file usci\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
