.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/util.h" 3 "Mon Nov 30 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/util.h
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fB_group_64\fP"
.br
.ti -1c
.RI "union \fB_group_32\fP"
.br
.ti -1c
.RI "union \fB_group_16\fP"
.br
.ti -1c
.RI "struct \fBCircBuffer_\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef union \fB_group_64\fP \fBgroup_64\fP"
.br
.ti -1c
.RI "typedef union \fB_group_32\fP \fBgroup_32\fP"
.br
.ti -1c
.RI "typedef union \fB_group_16\fP \fBgroup_16\fP"
.br
.ti -1c
.RI "typedef struct \fBCircBuffer_\fP \fBCircBuffer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBUTIL_modAdd\fP (int x, int y, int M)"
.br
.ti -1c
.RI "int \fBUTIL_getCircBufferSpace\fP (\fBCircBuffer\fP *pCb)"
.br
.ti -1c
.RI "int \fBUTIL_putToCircBuffer\fP (\fBCircBuffer\fP *pCb, unsigned char x)"
.br
.ti -1c
.RI "unsigned char \fBUTIL_getFromCircBuffer\fP (\fBCircBuffer\fP *pCb)"
.br
.ti -1c
.RI "unsigned int \fBUTIL_calcChecksum\fP (unsigned char *pStart, unsigned int len)"
.br
.ti -1c
.RI "unsigned int \fBUTIL_calcChecksumFlash\fP (unsigned long startAddr, unsigned int len)"
.br
.ti -1c
.RI "unsigned int \fBUTIL_decimalToBcd\fP (unsigned int dec)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FALSE   0"

.PP
Definition at line 18 of file util\&.h\&.
.SS "#define TRUE   1"

.PP
Definition at line 17 of file util\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBCircBuffer_\fP \fBCircBuffer\fP"

.SS "typedef union \fB_group_16\fP \fBgroup_16\fP"

.SS "typedef union \fB_group_32\fP \fBgroup_32\fP"

.SS "typedef union \fB_group_64\fP \fBgroup_64\fP"

.SH "Function Documentation"
.PP 
.SS "unsigned int UTIL_calcChecksum (unsigned char * pStart, unsigned int len)"

.PP
Definition at line 51 of file util\&.c\&.
.SS "unsigned int UTIL_calcChecksumFlash (unsigned long startAddr, unsigned int len)"

.PP
Definition at line 61 of file util\&.c\&.
.SS "unsigned int UTIL_decimalToBcd (unsigned int dec)"

.PP
Definition at line 71 of file util\&.c\&.
.SS "int UTIL_getCircBufferSpace (\fBCircBuffer\fP * pCb)"

.PP
Definition at line 23 of file util\&.c\&.
.SS "unsigned char UTIL_getFromCircBuffer (\fBCircBuffer\fP * pCb)"

.PP
Definition at line 40 of file util\&.c\&.
.SS "int UTIL_modAdd (int x, int y, int M)"

.PP
Definition at line 15 of file util\&.c\&.
.SS "int UTIL_putToCircBuffer (\fBCircBuffer\fP * pCb, unsigned char x)"

.PP
Definition at line 29 of file util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
