.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/variant.h" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/variant.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhware_info_\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAER05_RACK\fP   0"
.br
.ti -1c
.RI "#define \fBAER07_WALL\fP   1"
.br
.ti -1c
.RI "#define \fBAER_PRODUCT_ID\fP   \fBAER07_WALL\fP"
.br
.ti -1c
.RI "#define \fBVAR_VERSION_NUMBER\fP   303"
.br
.ti -1c
.RI "#define \fBVAR_VERSION_NUMBER_STR\fP   'V3\&.03'"
.br
.ti -1c
.RI "#define \fBMODEL_ID_HV\fP   1"
.br
.ti -1c
.RI "#define \fBMODEL_ID_MV\fP   0"
.br
.ti -1c
.RI "#define \fBDEVICE_ID\fP   0x41303031ul"
.br
.ti -1c
.RI "#define \fBDIGITAL_TEMP\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBhware_info_\fP \fBhware_info\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBVAR_retreive_hware\fP (void)"
.br
.ti -1c
.RI "void \fBVAR_SAFETY_setLimits\fP (void)"
.br
.ti -1c
.RI "void \fBVAR_CTRL_setFltrimParams\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBhware_info\fP \fBhware\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AER05_RACK   0"

.PP
Definition at line 15 of file variant\&.h\&.
.SS "#define AER07_WALL   1"

.PP
Definition at line 16 of file variant\&.h\&.
.SS "#define AER_PRODUCT_ID   \fBAER07_WALL\fP"

.PP
Definition at line 18 of file variant\&.h\&.
.SS "#define DEVICE_ID   0x41303031ul"

.PP
Definition at line 28 of file variant\&.h\&.
.SS "#define DIGITAL_TEMP"

.PP
Definition at line 34 of file variant\&.h\&.
.SS "#define MODEL_ID_HV   1"

.PP
Definition at line 24 of file variant\&.h\&.
.SS "#define MODEL_ID_MV   0"

.PP
Definition at line 25 of file variant\&.h\&.
.SS "#define VAR_VERSION_NUMBER   303"

.PP
Definition at line 19 of file variant\&.h\&.
.SS "#define VAR_VERSION_NUMBER_STR   'V3\&.03'"

.PP
Definition at line 20 of file variant\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBhware_info_\fP \fBhware_info\fP"

.SH "Function Documentation"
.PP 
.SS "void VAR_CTRL_setFltrimParams (void)\fC [inline]\fP"

.PP
Definition at line 57 of file variant\&.c\&.
.SS "void VAR_retreive_hware (void)\fC [inline]\fP"

.PP
Definition at line 35 of file variant\&.c\&.
.SS "void VAR_SAFETY_setLimits (void)\fC [inline]\fP"

.PP
Definition at line 45 of file variant\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBhware_info\fP hware\fC [extern]\fP"
#include 'lcd\&.h' include 'meas\&.h' 
.PP
Definition at line 18 of file variant\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
