.TH "D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/variant.c" 3 "Sun Nov 29 2020" "Version 9" "Charger6kW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/userSSD/github/Charger6kW/MSP_STM_9_RDD_plusMSP/MSP430/variant.c
.SH SYNOPSIS
.br
.PP
\fC#include 'variant\&.h'\fP
.br
\fC#include 'ctrl\&.h'\fP
.br
\fC#include 'safety\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBVAR_retreive_hware\fP (void)"
.br
.ti -1c
.RI "void \fBVAR_SAFETY_setLimits\fP (void)"
.br
.ti -1c
.RI "void \fBVAR_CTRL_setFltrimParams\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBhware_info\fP \fBhware\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void VAR_CTRL_setFltrimParams (void)\fC [inline]\fP"

.PP
Definition at line 57 of file variant\&.c\&.
.SS "void VAR_retreive_hware (void)\fC [inline]\fP"

.PP
Definition at line 35 of file variant\&.c\&.
.SS "void VAR_SAFETY_setLimits (void)\fC [inline]\fP"

.PP
Definition at line 45 of file variant\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBhware_info\fP hware"
\fBInitial value:\fP
.PP
.nf
=                               
        {
            DEVICE_ID,                          
            3,                                  




            MODEL_ID_HV,                        




            1,                                  
            0                                   
        }
.fi
#include 'lcd\&.h' include 'meas\&.h' 
.PP
Definition at line 18 of file variant\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Charger6kW from the source code\&.
